"""WU2 adapter contract cases.

Source: synthetic deterministic mappings written from the approved WU2 Plan.
Coverage: strict OSM POI and OSRM route normalization boundaries.
Non-coverage: live connectivity, real Jiangxi facts, provider completeness,
route quality, evidence scoring, feasibility, recommendation, or planning.

Expected values are handwritten from the frozen mapping rules. They are not
generated by the adapters under test.
"""

from __future__ import annotations

import copy
import unittest

from trip_decider.adapters import (
    IngestionContext,
    normalize_open_data_pois,
    normalize_route_evidence,
)


CHECKED_AT = "2026-07-28T00:00:00+08:00"
RETRIEVED_AT = "2026-07-28T08:00:00+08:00"
REQUEST_ID = "urn:uuid:00000001-0000-4000-8000-000000000001"
FROM_CANDIDATE = "candidate_00000001-0000-4000-8000-000000000001"
TO_CANDIDATE = "candidate_00000002-0000-4000-8000-000000000002"


def open_policy() -> dict[str, object]:
    return {
        "source_class": "open_data",
        "capture_mode": "persistent_anchor",
        "storage_policy": "persistent_allowed",
        "replay_allowed": True,
        "fixture_allowed": True,
        "policy_checked_at": CHECKED_AT,
        "terms_url": "https://www.openstreetmap.org/copyright",
        "authorization_ref": None,
        "license": {
            "identifier": "ODbL-1.0",
            "url": "https://opendatacommons.org/licenses/odbl/1-0/",
            "attribution": "© OpenStreetMap contributors",
        },
    }


def context() -> IngestionContext:
    return IngestionContext(
        request_ref={
            "artifact_id": REQUEST_ID,
            "artifact_type": "request",
            "payload_sha256": "a" * 64,
            "schema_version": "0.1.0",
        },
        run_id="run_00000001-0000-4000-8000-000000000001",
        created_at=RETRIEVED_AT,
    )


def poi_element(
    *,
    element_type: str = "node",
    element_id: int = 101,
    name: str = "Synthetic POI",
) -> dict[str, object]:
    element: dict[str, object] = {
        "type": element_type,
        "id": element_id,
        "tags": {
            "name": name,
            "tourism": "attraction",
        },
    }
    if element_type == "node":
        element["lat"] = 29.1
        element["lon"] = 117.2
    else:
        element["center"] = {"lat": 29.3, "lon": 117.4}
    return element


def poi_snapshot(*elements: dict[str, object]) -> dict[str, object]:
    selected = list(elements) if elements else [poi_element()]
    return {
        "format_version": "0.1.0",
        "provider": "osm",
        "operation": "overpass-poi-snapshot",
        "crs": "WGS84",
        "retrieved_at": RETRIEVED_AT,
        "request_fingerprint": "b" * 64,
        "response_locator": {
            "kind": "response_location",
            "value": "synthetic-poi.json",
        },
        "data_policy": open_policy(),
        "result": {
            "status": "success",
            "document": {
                "version": 0.6,
                "generator": "Overpass API",
                "osm3s": {"timestamp_osm_base": "2026-07-28T00:00:00Z"},
                "elements": selected,
            },
        },
    }


def route_record() -> dict[str, object]:
    return {
        "route_id": "route-1",
        "from_candidate_ref": FROM_CANDIDATE,
        "to_candidate_ref": TO_CANDIDATE,
        "mode": "driving",
        "coordinate_order": "longitude,latitude",
        "request_coordinates": [
            {"longitude": 117.1, "latitude": 29.1},
            {"longitude": 117.2, "latitude": 29.2},
        ],
        "request_fingerprint": "c" * 64,
        "response_locator": {
            "kind": "response_location",
            "value": "synthetic-routes.json#/routes/0/response",
        },
        "response": {
            "code": "Ok",
            "routes": [
                {
                    "distance": 12345.6,
                    "duration": 3600.0,
                    "weight": 3600.0,
                    "weight_name": "routability",
                }
            ],
        },
    }


def route_snapshot(*records: dict[str, object]) -> dict[str, object]:
    selected = list(records) if records else [route_record()]
    return {
        "format_version": "0.1.0",
        "provider": "osrm",
        "operation": "route/v1/driving",
        "crs": "WGS84",
        "retrieved_at": RETRIEVED_AT,
        "request_fingerprint": "d" * 64,
        "response_locator": {
            "kind": "response_location",
            "value": "synthetic-routes.json",
        },
        "data_policy": open_policy(),
        "result": {
            "status": "success",
            "document": {"routes": selected},
        },
    }


class AdapterContractCase(unittest.TestCase):
    maxDiff = None

    def assert_problem(
        self,
        result: object,
        code: str,
        pointer: str,
        rule: str,
    ) -> None:
        problems = getattr(result, "problems")
        self.assertEqual(len(problems), 1)
        self.assertEqual(problems[0].error_code, code)
        self.assertEqual(problems[0].json_pointer, pointer)
        self.assertEqual(problems[0].schema_rule, rule)

    def test_p01_exact_happy_path_candidate_fields(self) -> None:
        result = normalize_open_data_pois(poi_snapshot(), context())
        self.assertEqual(result.problems, ())
        artifact = result.value
        self.assertIsNotNone(artifact)
        candidate = artifact["payload"]["candidates"][0]
        self.assertEqual(
            candidate["candidate_id"],
            "candidate_8f330e07-0839-4696-8769-19ef50625ec0",
        )
        self.assertEqual(candidate["label"], "Synthetic POI")
        self.assertEqual(candidate["candidate_kind"], "poi")
        self.assertEqual(candidate["provider"]["name"], "osm")
        self.assertEqual(candidate["provider"]["record_id"], "101")
        self.assertEqual(candidate["provider"]["record_type"], "node")
        self.assertEqual(
            candidate["provider"]["categories"],
            [{"code": "tourism=attraction", "label": "attraction"}],
        )
        self.assertEqual(candidate["location"]["crs"], "WGS84")
        self.assertEqual(candidate["location"]["latitude"], 29.1)
        self.assertEqual(candidate["location"]["longitude"], 117.2)
        self.assertEqual(
            candidate["location"]["source_refs"],
            [{"kind": "provider_item", "value": "osm:node:101"}],
        )
        self.assertEqual(artifact["payload"]["generation_stage"], "poi_discovery")

    def test_p02_response_order_independent_candidate_ordering(self) -> None:
        first = poi_element(element_type="way", element_id=202, name="Second")
        second = poi_element(element_type="node", element_id=101, name="First")
        forward = normalize_open_data_pois(poi_snapshot(first, second), context())
        reverse = normalize_open_data_pois(poi_snapshot(second, first), context())
        self.assertEqual(forward.problems, ())
        self.assertEqual(reverse.problems, ())
        self.assertEqual(forward.value, reverse.value)
        self.assertEqual(
            [
                item["candidate_id"]
                for item in forward.value["payload"]["candidates"]
            ],
            [
                "candidate_8f330e07-0839-4696-8769-19ef50625ec0",
                "candidate_b6b4862e-c519-4454-80e2-597c73b739f3",
            ],
        )

    def test_p03_missing_coordinates_hard_fails(self) -> None:
        snapshot = poi_snapshot()
        del snapshot["result"]["document"]["elements"][0]["lat"]
        result = normalize_open_data_pois(snapshot, context())
        self.assert_problem(
            result,
            "INGESTION_RECORD_INVALID",
            "/result/document/elements/0",
            "coordinates",
        )

    def test_p04_missing_crs_hard_fails(self) -> None:
        snapshot = poi_snapshot()
        del snapshot["crs"]
        result = normalize_open_data_pois(snapshot, context())
        self.assert_problem(
            result,
            "INGESTION_CRS_MISSING",
            "/crs",
            "required",
        )

    def test_p05_missing_provider_hard_fails(self) -> None:
        snapshot = poi_snapshot()
        del snapshot["provider"]
        result = normalize_open_data_pois(snapshot, context())
        self.assert_problem(
            result,
            "INGESTION_PROVIDER_MISSING",
            "/provider",
            "required",
        )

    def test_p06_empty_response_hard_fails(self) -> None:
        snapshot = poi_snapshot()
        snapshot["result"]["document"]["elements"] = []
        result = normalize_open_data_pois(snapshot, context())
        self.assert_problem(
            result,
            "INGESTION_RESPONSE_EMPTY",
            "/result/document/elements",
            "minItems",
        )

    def test_p07_provider_error_hard_fails(self) -> None:
        snapshot = poi_snapshot()
        snapshot["result"] = {
            "status": "error",
            "provider_error_code": "transport_error",
        }
        result = normalize_open_data_pois(snapshot, context())
        self.assert_problem(
            result,
            "INGESTION_PROVIDER_ERROR",
            "/result/provider_error_code",
            "providerStatus",
        )

    def test_p08_missing_exact_name_hard_fails(self) -> None:
        snapshot = poi_snapshot()
        del snapshot["result"]["document"]["elements"][0]["tags"]["name"]
        result = normalize_open_data_pois(snapshot, context())
        self.assert_problem(
            result,
            "INGESTION_RECORD_INVALID",
            "/result/document/elements/0/tags/name",
            "required",
        )

    def test_p09_missing_category_hard_fails(self) -> None:
        snapshot = poi_snapshot()
        del snapshot["result"]["document"]["elements"][0]["tags"]["tourism"]
        result = normalize_open_data_pois(snapshot, context())
        self.assert_problem(
            result,
            "INGESTION_RECORD_INVALID",
            "/result/document/elements/0/tags",
            "providerCategory",
        )

    def test_p10_non_replay_policy_hard_fails(self) -> None:
        snapshot = poi_snapshot()
        snapshot["data_policy"]["replay_allowed"] = False
        result = normalize_open_data_pois(snapshot, context())
        self.assert_problem(
            result,
            "INGESTION_POLICY_INVALID",
            "/data_policy",
            "openDataAnchorPolicy",
        )

    def test_r01_exact_happy_path_evidence_fields(self) -> None:
        result = normalize_route_evidence(route_snapshot(), context())
        self.assertEqual(result.problems, ())
        artifact = result.value
        self.assertIsNotNone(artifact)
        fact = artifact["payload"]["facts"][0]
        self.assertEqual(
            fact["fact_id"],
            "fact_a3e79852-a23a-46b5-b672-3d5b6bc07746",
        )
        self.assertEqual(fact["subject"]["from_candidate_ref"], FROM_CANDIDATE)
        self.assertEqual(fact["subject"]["to_candidate_ref"], TO_CANDIDATE)
        self.assertEqual(fact["field"], "travel_time")
        self.assertEqual(fact["value"], 3600.0)
        self.assertEqual(fact["unit"], "second")
        self.assertEqual(fact["support_status"], "sourced")
        self.assertEqual(fact["derivation"], "api_estimate")
        self.assertEqual(fact["display_status"], "estimated")
        self.assertEqual(fact["freshness"]["status"], "unknown")
        self.assertEqual(fact["sources"][0]["provider"], "osrm")
        self.assertEqual(
            fact["sources"][0]["request_fingerprint"],
            "c" * 64,
        )
        self.assertEqual(
            fact["derivation_detail"]["estimate"],
            {
                "method": "osrm-route-v1-driving",
                "value": 3600.0,
                "unit": "second",
            },
        )

    def test_r02_wrong_coordinate_order_hard_fails(self) -> None:
        snapshot = route_snapshot()
        snapshot["result"]["document"]["routes"][0][
            "coordinate_order"
        ] = "latitude,longitude"
        result = normalize_route_evidence(snapshot, context())
        self.assert_problem(
            result,
            "INGESTION_INPUT_INVALID",
            "/result/document/routes/0/coordinate_order",
            "coordinateOrder",
        )

    def test_r03_missing_crs_hard_fails(self) -> None:
        snapshot = route_snapshot()
        del snapshot["crs"]
        result = normalize_route_evidence(snapshot, context())
        self.assert_problem(
            result,
            "INGESTION_CRS_MISSING",
            "/crs",
            "required",
        )

    def test_r04_missing_provider_hard_fails(self) -> None:
        snapshot = route_snapshot()
        del snapshot["provider"]
        result = normalize_route_evidence(snapshot, context())
        self.assert_problem(
            result,
            "INGESTION_PROVIDER_MISSING",
            "/provider",
            "required",
        )

    def test_r05_empty_route_response_hard_fails(self) -> None:
        snapshot = route_snapshot()
        snapshot["result"]["document"]["routes"] = []
        result = normalize_route_evidence(snapshot, context())
        self.assert_problem(
            result,
            "INGESTION_RESPONSE_EMPTY",
            "/result/document/routes",
            "minItems",
        )

    def test_r06_non_ok_provider_code_hard_fails(self) -> None:
        snapshot = route_snapshot()
        snapshot["result"]["document"]["routes"][0]["response"]["code"] = "NoRoute"
        result = normalize_route_evidence(snapshot, context())
        self.assert_problem(
            result,
            "INGESTION_PROVIDER_ERROR",
            "/result/document/routes/0/response/code",
            "providerStatus",
        )

    def test_r07_missing_duration_hard_fails(self) -> None:
        snapshot = route_snapshot()
        del snapshot["result"]["document"]["routes"][0]["response"]["routes"][0][
            "duration"
        ]
        result = normalize_route_evidence(snapshot, context())
        self.assert_problem(
            result,
            "INGESTION_DURATION_INVALID",
            "/result/document/routes/0/response/routes/0/duration",
            "durationSecond",
        )

    def test_r08_invalid_duration_hard_fails(self) -> None:
        snapshot = route_snapshot()
        snapshot["result"]["document"]["routes"][0]["response"]["routes"][0][
            "duration"
        ] = -1
        result = normalize_route_evidence(snapshot, context())
        self.assert_problem(
            result,
            "INGESTION_DURATION_INVALID",
            "/result/document/routes/0/response/routes/0/duration",
            "durationSecond",
        )


if __name__ == "__main__":
    unittest.main()
