"""Deterministic WU2A-R acquisition failure-path contract cases.

Source:
    Synthetic transports, responses, exceptions, clocks, and payload bytes
    are handwritten from the approved WU2A-R Plan.  Expected values are
    specification-authored and are not generated by the harness under test.

Coverage:
    Ledger-first persistence, stable HTTP/transport/internal classification,
    transport-only retry relations, explicit null preservation, and terminal
    persistence for ordinary Python failure paths.

Not covered:
    Live networking, forced process termination, provider behavior, OSM
    coverage, query correctness, anchors, fixtures, adapters, evidence,
    recommendation, routing, or planning.
"""

from __future__ import annotations

import hashlib
import json
import socket
import tempfile
import unittest
from email.message import Message
from io import BytesIO
from pathlib import Path
from urllib.error import HTTPError, URLError

from scripts.acquisition_harness import (
    ATTEMPT_FIELDS,
    TransportResponse,
    run_acquisition,
)


ENDPOINT = "https://example.invalid/injected-only"
PURPOSE = "synthetic deterministic acquisition"
REQUEST_BYTES = b"[out:json];synthetic-contract-input"
REQUEST_SHA256 = hashlib.sha256(REQUEST_BYTES).hexdigest()


class SequenceTransport:
    """Return or raise handwritten outcomes without performing network I/O."""

    def __init__(self, *outcomes: object) -> None:
        self._outcomes = list(outcomes)
        self.requests: list[bytes] = []

    def __call__(self, request_bytes: bytes) -> TransportResponse:
        self.requests.append(request_bytes)
        if not self._outcomes:
            raise AssertionError("transport called more often than specified")
        outcome = self._outcomes.pop(0)
        if isinstance(outcome, BaseException):
            raise outcome
        if not isinstance(outcome, TransportResponse):
            raise AssertionError("malformed synthetic transport outcome")
        return outcome


class FixedClock:
    """Emit a finite, specification-authored RFC 3339 sequence."""

    def __init__(self, attempt_count: int) -> None:
        self._values = iter(
            f"2026-07-28T10:00:{second:02d}+08:00"
            for second in range(attempt_count * 2)
        )

    def __call__(self) -> str:
        return next(self._values)


def http_error(
    status: int,
    body: bytes | None,
    *,
    reason: str = "synthetic reason",
    content_type: str | None = "text/plain; charset=utf-8",
) -> HTTPError:
    headers = Message()
    if content_type is not None:
        headers["Content-Type"] = content_type
    stream = None if body is None else BytesIO(body)
    return HTTPError(ENDPOINT, status, reason, headers, stream)


class AcquisitionHarnessCase(unittest.TestCase):
    maxDiff = None

    def setUp(self) -> None:
        self._temporary_directory = tempfile.TemporaryDirectory(
            prefix="trip-decider-wu2ar-test-"
        )
        self.addCleanup(self._temporary_directory.cleanup)
        self.temp_root = Path(self._temporary_directory.name)
        self.ledger_path = self.temp_root / "ledger.json"

    def run_case(
        self,
        transport: SequenceTransport,
        *,
        attempt_count: int,
        max_transport_retries: int = 1,
        postprocess=None,
    ):
        return run_acquisition(
            purpose=PURPOSE,
            endpoint=ENDPOINT,
            method="POST",
            request_bytes=REQUEST_BYTES,
            ledger_path=self.ledger_path,
            transport=transport,
            clock=FixedClock(attempt_count),
            max_transport_retries=max_transport_retries,
            postprocess=postprocess,
        )

    def assert_complete_attempt(self, attempt: dict[str, object]) -> None:
        self.assertEqual(tuple(attempt), ATTEMPT_FIELDS)
        self.assertEqual(attempt["purpose"], PURPOSE)
        self.assertEqual(attempt["endpoint"], ENDPOINT)
        self.assertEqual(attempt["method"], "POST")
        self.assertEqual(attempt["request_sha256"], REQUEST_SHA256)
        self.assertIsNotNone(attempt["started_at"])
        self.assertIsNotNone(attempt["completed_at"])
        self.assertNotEqual(attempt["status"], "started")

    def assert_persisted(self, result) -> dict[str, object]:
        self.assertEqual(result.ledger_path, self.ledger_path)
        persisted = json.loads(self.ledger_path.read_text(encoding="utf-8"))
        self.assertEqual(persisted["attempts"], list(result.attempts))
        self.assertEqual(persisted["retries"], list(result.retries))
        self.assertEqual(list(self.temp_root.glob("*.tmp")), [])
        return persisted

    def test_a01_http_400_is_complete_and_not_retried(self) -> None:
        body = b"bad query"
        transport = SequenceTransport(http_error(400, body))

        result = self.run_case(transport, attempt_count=1)

        self.assertEqual(len(transport.requests), 1)
        self.assertEqual(len(result.attempts), 1)
        self.assertEqual(result.retries, ())
        attempt = result.attempts[0]
        self.assert_complete_attempt(attempt)
        self.assertEqual(attempt["status"], "http_response_failure")
        self.assertEqual(attempt["error_class"], "http_response_failure")
        self.assertEqual(attempt["http_status"], 400)
        self.assertEqual(attempt["response_bytes"], len(body))
        self.assertEqual(
            attempt["response_sha256"],
            hashlib.sha256(body).hexdigest(),
        )
        self.assertEqual(
            attempt["content_type"],
            "text/plain; charset=utf-8",
        )
        self.assertEqual(attempt["retry_decision"], "not_retryable_http")
        self.assert_persisted(result)

    def test_a02_timeout_retries_once_then_succeeds(self) -> None:
        transport = SequenceTransport(
            TimeoutError("synthetic timeout detail"),
            TransportResponse(200, b"ok", "application/json"),
        )

        result = self.run_case(transport, attempt_count=2)

        self.assertEqual(transport.requests, [REQUEST_BYTES, REQUEST_BYTES])
        self.assertEqual(len(result.attempts), 2)
        first, second = result.attempts
        self.assert_complete_attempt(first)
        self.assert_complete_attempt(second)
        self.assertEqual(first["status"], "transport_failure")
        self.assertEqual(first["retry_decision"], "retry_scheduled")
        self.assertEqual(second["status"], "succeeded")
        self.assertEqual(second["retry_decision"], "not_applicable")
        self.assertEqual(
            result.retries,
            (
                {
                    "original_attempt_id": "attempt-0001",
                    "retry_attempt_id": "attempt-0002",
                    "same_request_sha256": True,
                    "reason": "transport_failure",
                },
            ),
        )
        self.assert_persisted(result)

    def test_a03_dns_failure_is_transport_and_retryable(self) -> None:
        private_detail = "private-dns-detail-must-not-be-persisted"
        transport = SequenceTransport(
            URLError(socket.gaierror(11001, private_detail)),
            TransportResponse(200, b"dns-recovered", "application/json"),
        )

        result = self.run_case(transport, attempt_count=2)

        first = result.attempts[0]
        self.assert_complete_attempt(first)
        self.assertEqual(first["status"], "transport_failure")
        self.assertEqual(first["error_class"], "transport_failure")
        self.assertEqual(first["http_status"], None)
        self.assertEqual(first["response_sha256"], None)
        self.assertEqual(first["retry_decision"], "retry_scheduled")
        self.assertEqual(len(result.retries), 1)
        persisted = self.assert_persisted(result)
        self.assertNotIn(private_detail, json.dumps(persisted))

    def test_a04_retry_exhaustion_stops_with_complete_ledger(self) -> None:
        transport = SequenceTransport(
            ConnectionError("first private detail"),
            TimeoutError("second private detail"),
        )

        result = self.run_case(transport, attempt_count=2)

        self.assertEqual(len(transport.requests), 2)
        self.assertEqual(len(result.attempts), 2)
        first, second = result.attempts
        self.assert_complete_attempt(first)
        self.assert_complete_attempt(second)
        self.assertEqual(first["retry_decision"], "retry_scheduled")
        self.assertEqual(second["status"], "transport_failure")
        self.assertEqual(second["retry_decision"], "retry_exhausted")
        self.assertEqual(len(result.retries), 1)
        persisted = self.assert_persisted(result)
        persisted_text = json.dumps(persisted)
        self.assertNotIn("first private detail", persisted_text)
        self.assertNotIn("second private detail", persisted_text)

    def test_a05_postprocess_failure_is_finalized(self) -> None:
        body = b"response-before-process-failure"
        transport = SequenceTransport(
            TransportResponse(200, body, "application/json")
        )

        def fail_after_response(_response: TransportResponse) -> None:
            raise RuntimeError("private postprocess failure detail")

        result = self.run_case(
            transport,
            attempt_count=1,
            postprocess=fail_after_response,
        )

        self.assertEqual(len(transport.requests), 1)
        attempt = result.attempts[0]
        self.assert_complete_attempt(attempt)
        self.assertEqual(attempt["status"], "internal_failure")
        self.assertEqual(attempt["error_class"], "internal_failure")
        self.assertEqual(attempt["http_status"], 200)
        self.assertEqual(attempt["response_bytes"], len(body))
        self.assertEqual(
            attempt["response_sha256"],
            hashlib.sha256(body).hexdigest(),
        )
        self.assertEqual(attempt["retry_decision"], "not_retryable_internal")
        persisted = self.assert_persisted(result)
        self.assertNotIn(
            "private postprocess failure detail",
            json.dumps(persisted),
        )

    def test_a06_unknown_body_metadata_remains_null(self) -> None:
        private_detail = "do-not-reconstruct-deadbeef"
        transport = SequenceTransport(
            http_error(404, None, reason=private_detail)
        )

        result = self.run_case(transport, attempt_count=1)

        attempt = result.attempts[0]
        self.assert_complete_attempt(attempt)
        self.assertEqual(attempt["status"], "http_response_failure")
        self.assertEqual(attempt["http_status"], 404)
        self.assertEqual(attempt["response_bytes"], None)
        self.assertEqual(attempt["response_sha256"], None)
        self.assertEqual(attempt["retry_decision"], "not_retryable_http")
        persisted = self.assert_persisted(result)
        self.assertIsNone(persisted["attempts"][0]["response_bytes"])
        self.assertIsNone(persisted["attempts"][0]["response_sha256"])
        self.assertNotIn(private_detail, json.dumps(persisted))

    def test_a07_returned_http_500_is_not_retried(self) -> None:
        body = b"provider failure body"
        transport = SequenceTransport(
            TransportResponse(500, body, "application/problem+json")
        )

        result = self.run_case(
            transport,
            attempt_count=1,
            max_transport_retries=3,
        )

        self.assertEqual(len(transport.requests), 1)
        self.assertEqual(result.retries, ())
        attempt = result.attempts[0]
        self.assert_complete_attempt(attempt)
        self.assertEqual(attempt["status"], "http_response_failure")
        self.assertEqual(attempt["http_status"], 500)
        self.assertEqual(attempt["response_bytes"], len(body))
        self.assertEqual(
            attempt["response_sha256"],
            hashlib.sha256(body).hexdigest(),
        )
        self.assertEqual(attempt["retry_decision"], "not_retryable_http")
        self.assert_persisted(result)

    def test_a08_http_429_does_not_consume_retry_budget(self) -> None:
        transport = SequenceTransport(http_error(429, b"rate limited"))

        result = self.run_case(
            transport,
            attempt_count=1,
            max_transport_retries=3,
        )

        self.assertEqual(len(transport.requests), 1)
        self.assertEqual(result.retries, ())
        attempt = result.attempts[0]
        self.assert_complete_attempt(attempt)
        self.assertEqual(attempt["status"], "http_response_failure")
        self.assertEqual(attempt["http_status"], 429)
        self.assertEqual(attempt["error_class"], "http_response_failure")
        self.assertEqual(attempt["retry_decision"], "not_retryable_http")
        self.assert_persisted(result)

    def test_a09_connection_reset_retry_relation_is_exact(self) -> None:
        transport = SequenceTransport(
            ConnectionResetError("private reset detail"),
            TransportResponse(204, b"", None),
        )

        result = self.run_case(transport, attempt_count=2)

        self.assertEqual(len(transport.requests), 2)
        self.assertEqual(
            result.attempts[0]["request_sha256"],
            result.attempts[1]["request_sha256"],
        )
        self.assertEqual(
            result.retries[0],
            {
                "original_attempt_id": "attempt-0001",
                "retry_attempt_id": "attempt-0002",
                "same_request_sha256": True,
                "reason": "transport_failure",
            },
        )
        self.assertEqual(result.attempts[0]["status"], "transport_failure")
        self.assertEqual(result.attempts[1]["status"], "succeeded")
        self.assert_complete_attempt(result.attempts[0])
        self.assert_complete_attempt(result.attempts[1])
        self.assert_persisted(result)

    def test_a10_clean_success_has_complete_response_metadata(self) -> None:
        body = b""
        transport = SequenceTransport(TransportResponse(204, body, None))

        result = self.run_case(transport, attempt_count=1)

        self.assertEqual(len(transport.requests), 1)
        self.assertEqual(result.retries, ())
        attempt = result.attempts[0]
        self.assert_complete_attempt(attempt)
        self.assertEqual(attempt["status"], "succeeded")
        self.assertEqual(attempt["http_status"], 204)
        self.assertEqual(attempt["response_bytes"], 0)
        self.assertEqual(
            attempt["response_sha256"],
            hashlib.sha256(body).hexdigest(),
        )
        self.assertEqual(attempt["content_type"], None)
        self.assertEqual(attempt["error_class"], None)
        self.assertEqual(attempt["retry_decision"], "not_applicable")
        self.assert_persisted(result)


if __name__ == "__main__":
    unittest.main()
