"""WU5 fixture-first cases over the committed real offline anchor.

The planning inputs reuse the independently handwritten WU4 test builder.
Expected HTML text, file layout, hashes, and failure behavior are frozen here;
they are not generated by the E2E implementation or its rendered output.
"""

from __future__ import annotations

import hashlib
from html.parser import HTMLParser
import json
import os
from pathlib import Path
import socket
import tempfile
import unittest
import urllib.request
from unittest.mock import patch

import trip_decider.e2e_demo as e2e_module
from tests.test_wu4_coarse_planner import (
    ANCHOR,
    HUANGLING_REFS,
    JIANGLING_REF,
    LIKENG_REF,
    _write_planning_root,
)
from trip_decider.coarse_planner import run_coarse_planner as real_planner
from trip_decider.e2e_demo import run_e2e_demo
from trip_decider.evidence_runtime import (
    run_evidence_runtime as real_evidence,
)
from trip_decider.recovery import run_wu2_recovery as real_recovery
from trip_decider.schema_validation import ValidationProblem, ValidationResult


EXPECTED_FILES = (
    "evidence/evidence-gate.json",
    "evidence/evidence.json",
    "evidence/run-summary.json",
    "planning/plan.json",
    "planning/planning-gate.json",
    "planning/run-summary.json",
    "planning/violations.json",
    "recovery/candidates.json",
    "recovery/record-local-facts.json",
    "recovery/run-summary.json",
    "recovery/seed-accounting.json",
    "report/index.html",
    "run-summary.json",
)
EXPECTED_LINKS = (
    "../planning/plan.json",
    "../planning/violations.json",
    "../planning/planning-gate.json",
    "../evidence/evidence.json",
    "../recovery/candidates.json",
)
EXPECTED_CONDITIONS = (
    (
        "condition_route_evidence_unavailable",
        "Route evidence is unavailable; no route is asserted.",
    ),
    (
        "condition_opening_hours_evidence_unavailable",
        "Opening-hours evidence is unavailable.",
    ),
    (
        "condition_activity_duration_unavailable",
        "Activity duration evidence is unavailable.",
    ),
    (
        "condition_specific_activity_times_unscheduled",
        "Activities are assigned to dates without specific times.",
    ),
    (
        "condition_candidate_admission_blockers_remain",
        (
            "Identity or evidence blockers remain; exact details are "
            "retained in the planning gate."
        ),
    ),
)


def _json(path: Path) -> dict[str, object]:
    value = json.loads(path.read_text(encoding="utf-8"))
    if not isinstance(value, dict):
        raise AssertionError("expected JSON object")
    return value


def _sha256(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest().upper()


def _files(root: Path) -> tuple[str, ...]:
    return tuple(
        sorted(
            path.relative_to(root).as_posix()
            for path in root.rglob("*")
            if path.is_file()
        )
    )


def _file_bytes(root: Path) -> dict[str, bytes]:
    return {
        relative: root.joinpath(*relative.split("/")).read_bytes()
        for relative in _files(root)
    }


def _staging_residue(parent: Path, output_name: str) -> tuple[Path, ...]:
    return tuple(
        path
        for path in parent.iterdir()
        if path.name.startswith(f".{output_name}.")
        and path.name.endswith(".staging")
    )


class _StructureParser(HTMLParser):
    def __init__(self) -> None:
        super().__init__(convert_charrefs=True)
        self.section_ids: list[str] = []
        self.links: list[str] = []
        self.tags: list[str] = []

    def handle_starttag(
        self,
        tag: str,
        attrs: list[tuple[str, str | None]],
    ) -> None:
        self.tags.append(tag)
        values = dict(attrs)
        if tag == "section" and isinstance(values.get("id"), str):
            self.section_ids.append(values["id"])
        if tag == "a" and isinstance(values.get("href"), str):
            self.links.append(values["href"])


class EndToEndDemoCase(unittest.TestCase):
    """Six independent behaviors across the real offline pipeline."""

    def setUp(self) -> None:
        self.temporary = tempfile.TemporaryDirectory(
            prefix="trip-decider-wu5-e2e-"
        )
        self.temp_root = Path(self.temporary.name)

    def tearDown(self) -> None:
        self.temporary.cleanup()

    def _planning_root(
        self,
        name: str,
        *,
        day_count: int = 2,
    ) -> Path:
        root = self.temp_root / name
        _write_planning_root(root, day_count)
        return root

    def _run(
        self,
        name: str,
        *,
        day_count: int = 2,
        output_root: Path | None = None,
    ):
        planning_root = self._planning_root(
            f"{name}-planning",
            day_count=day_count,
        )
        destination = output_root or self.temp_root / f"{name}-output"
        with (
            patch.object(
                socket.socket,
                "connect",
                side_effect=AssertionError("network forbidden"),
            ) as socket_mock,
            patch.object(
                urllib.request,
                "urlopen",
                side_effect=AssertionError("network forbidden"),
            ) as urlopen_mock,
        ):
            result = run_e2e_demo(ANCHOR, planning_root, destination)
        self.assertEqual(socket_mock.call_count, 0)
        self.assertEqual(urlopen_mock.call_count, 0)
        return planning_root, destination, result

    def test_e2e01_real_anchor_emits_complete_layout(self) -> None:
        _, output_root, result = self._run("e2e01")
        self.assertEqual(result.problems, ())
        self.assertIsNotNone(result.value)
        self.assertEqual(_files(output_root), EXPECTED_FILES)

        summary = _json(output_root / "run-summary.json")
        planning_summary = _json(
            output_root / "planning" / "run-summary.json"
        )
        self.assertEqual(
            set(summary),
            {
                "schema_version",
                "run_id",
                "completion_status",
                "input",
                "stages",
                "result",
                "report",
                "network_attempts",
                "llm_calls",
            },
        )
        self.assertEqual(summary["schema_version"], "wu5-e2e-demo-run/1.0")
        self.assertEqual(summary["run_id"], planning_summary["run_id"])
        self.assertEqual(summary["completion_status"], "completed")
        self.assertEqual(
            summary["result"],
            {
                "planning_status": "conditionally_feasible",
                "draft_created": True,
                "publishable": False,
                "generation_allowed_input": False,
                "scheduled_count": 2,
                "blocked_count": 2,
            },
        )
        self.assertEqual(summary["network_attempts"], 0)
        self.assertEqual(summary["llm_calls"], 0)
        self.assertNotIn("run_summary_sha256", summary)
        for stage_name in ("recovery", "evidence", "planning"):
            stage = summary["stages"][stage_name]
            stage_path = output_root.joinpath(
                *stage["summary_path"].split("/")
            )
            self.assertEqual(stage["summary_sha256"], _sha256(stage_path))
        self.assertEqual(
            summary["report"]["sha256"],
            _sha256(output_root / "report" / "index.html"),
        )
        self.assertNotIn(
            str(self.temp_root),
            json.dumps(summary, ensure_ascii=False, sort_keys=True),
        )

    def test_e2e02_html_shows_only_unscheduled_coarse_days(self) -> None:
        _, output_root, result = self._run("e2e02")
        self.assertEqual(result.problems, ())
        self.assertIsNotNone(result.value)
        raw = (output_root / "report" / "index.html").read_bytes()
        self.assertFalse(raw.startswith(b"\xef\xbb\xbf"))
        html_text = raw.decode("utf-8", errors="strict")
        parser = _StructureParser()
        parser.feed(html_text)

        self.assertEqual(
            parser.section_ids,
            [
                "status",
                "itinerary",
                "blockers",
                "evidence",
                "conditions",
                "audit",
            ],
        )
        self.assertEqual(tuple(parser.links), EXPECTED_LINKS)
        self.assertNotIn("script", parser.tags)
        self.assertNotIn("img", parser.tags)
        self.assertNotIn("link", parser.tags)
        self.assertIn("第1天", html_text)
        self.assertIn("江岭", html_text)
        self.assertIn("第2天", html_text)
        self.assertIn("李坑", html_text)
        self.assertEqual(html_text.count("具体时刻：尚未安排"), 2)
        self.assertNotIn("start_at", html_text)
        self.assertNotIn("end_at", html_text)
        for forbidden in (
            "推荐顺序",
            "最佳路线",
            "建议上午",
            "预计游览时长",
            "距离",
            "交通耗时",
            "热度",
            "优化分数",
        ):
            self.assertNotIn(forbidden, html_text)

    def test_e2e03_html_preserves_identity_blockers(self) -> None:
        _, output_root, result = self._run("e2e03")
        self.assertEqual(result.problems, ())
        self.assertIsNotNone(result.value)
        html_text = (
            output_root / "report" / "index.html"
        ).read_text(encoding="utf-8")

        self.assertIn("篁岭", html_text)
        self.assertIn("BLOCKED_IDENTITY_AMBIGUOUS", html_text)
        self.assertIn("存在多个候选，需要确认", html_text)
        for candidate_ref in HUANGLING_REFS:
            self.assertIn(candidate_ref, html_text)
        self.assertNotIn("已选择篁岭候选", html_text)
        self.assertIn("庆源", html_text)
        self.assertIn("BLOCKED_IDENTITY_UNMATCHED", html_text)
        self.assertIn("当前候选池未匹配", html_text)
        self.assertIn("未创建占位地点", html_text)
        gate = _json(
            output_root / "planning" / "planning-gate.json"
        )
        self.assertEqual(gate["blocked_seeds"][1]["candidate_refs"], [])

    def test_e2e04_html_keeps_unknown_evidence_and_conditions(self) -> None:
        _, output_root, result = self._run("e2e04")
        self.assertEqual(result.problems, ())
        self.assertIsNotNone(result.value)
        html_text = (
            output_root / "report" / "index.html"
        ).read_text(encoding="utf-8")

        self.assertIn("support_status: unknown", html_text)
        self.assertIn("display_status: unknown", html_text)
        self.assertIn("publishable: false", html_text)
        self.assertIn("generation_allowed_input: false", html_text)
        self.assertIn("不能视为已核实事实", html_text)
        positions: list[int] = []
        for condition_id, description in EXPECTED_CONDITIONS:
            self.assertIn(condition_id, html_text)
            self.assertIn(description, html_text)
            positions.append(html_text.index(condition_id))
        self.assertEqual(positions, sorted(positions))
        for overclaim in ("数据已验证", "来源可靠", "官方确认", "实时数据"):
            self.assertNotIn(overclaim, html_text)

    def test_e2e05_no_plan_page_does_not_claim_infeasibility(self) -> None:
        _, output_root, result = self._run("e2e05", day_count=1)
        self.assertEqual(result.problems, ())
        self.assertIsNotNone(result.value)
        html_text = (
            output_root / "report" / "index.html"
        ).read_text(encoding="utf-8")
        parser = _StructureParser()
        parser.feed(html_text)

        self.assertIn("no-plan", parser.section_ids)
        self.assertNotIn("itinerary", parser.section_ids)
        self.assertIn("当前粗分配器未找到计划", html_text)
        self.assertIn(
            "INSUFFICIENT_DAY_CAPACITY_FOR_ONE_PER_DAY_ALLOCATOR",
            html_text,
        )
        self.assertIn(JIANGLING_REF, html_text)
        self.assertIn(LIKENG_REF, html_text)
        self.assertIn("江岭", html_text)
        self.assertIn("李坑", html_text)
        self.assertIn("这不等于已证明不可行", html_text)
        self.assertIn("publishable: false", html_text)
        self.assertNotIn("无法旅行", html_text)
        self.assertNotIn("行程不可行", html_text)
        self.assertNotIn("约束无解", html_text)
        self.assertNotIn("proof", html_text.lower())

    def test_e2e06_invocation_is_deterministic_atomic_and_offline(
        self,
    ) -> None:
        first_planning = self._planning_root("e2e06-first-planning")
        second_planning = self._planning_root("e2e06-second-planning")
        first_root = self.temp_root / "e2e06-first-output"
        second_root = self.temp_root / "e2e06-second-output"
        trace: list[str] = []

        def traced_recovery(*args, **kwargs):
            trace.append("recovery")
            return real_recovery(*args, **kwargs)

        def traced_evidence(*args, **kwargs):
            trace.append("evidence")
            return real_evidence(*args, **kwargs)

        def traced_planner(*args, **kwargs):
            trace.append("planning")
            return real_planner(*args, **kwargs)

        real_render = getattr(e2e_module, "_render_html", lambda *args: b"")
        real_install = getattr(
            e2e_module,
            "_install_directory",
            lambda *args: None,
        )

        def traced_render(*args, **kwargs):
            trace.append("render")
            return real_render(*args, **kwargs)

        def traced_install(*args, **kwargs):
            trace.append("install")
            return real_install(*args, **kwargs)

        with (
            patch(
                "trip_decider.e2e_demo.run_wu2_recovery",
                side_effect=traced_recovery,
                create=True,
            ) as recovery_mock,
            patch(
                "trip_decider.e2e_demo.run_evidence_runtime",
                side_effect=traced_evidence,
                create=True,
            ) as evidence_mock,
            patch(
                "trip_decider.e2e_demo.run_coarse_planner",
                side_effect=traced_planner,
                create=True,
            ) as planner_mock,
            patch(
                "trip_decider.e2e_demo._render_html",
                side_effect=traced_render,
                create=True,
            ) as render_mock,
            patch(
                "trip_decider.e2e_demo._install_directory",
                side_effect=traced_install,
                create=True,
            ) as install_mock,
            patch.object(
                socket.socket,
                "connect",
                side_effect=AssertionError("network forbidden"),
            ) as socket_mock,
            patch.object(
                urllib.request,
                "urlopen",
                side_effect=AssertionError("network forbidden"),
            ) as urlopen_mock,
        ):
            first = run_e2e_demo(ANCHOR, first_planning, first_root)
            second = run_e2e_demo(ANCHOR, second_planning, second_root)
        self.assertEqual(first.problems, ())
        self.assertEqual(second.problems, ())
        self.assertIsNotNone(first.value)
        self.assertIsNotNone(second.value)
        self.assertEqual(recovery_mock.call_count, 2)
        self.assertEqual(evidence_mock.call_count, 2)
        self.assertEqual(planner_mock.call_count, 2)
        self.assertEqual(render_mock.call_count, 2)
        self.assertEqual(install_mock.call_count, 2)
        self.assertEqual(
            trace,
            [
                "recovery",
                "evidence",
                "planning",
                "render",
                "install",
                "recovery",
                "evidence",
                "planning",
                "render",
                "install",
            ],
        )
        self.assertEqual(_file_bytes(first_root), _file_bytes(second_root))
        self.assertEqual(socket_mock.call_count, 0)
        self.assertEqual(urlopen_mock.call_count, 0)
        self.assertEqual(first.value.network_attempts, 0)
        self.assertEqual(first.value.llm_calls, 0)
        self.assertEqual(_staging_residue(self.temp_root, first_root.name), ())
        self.assertEqual(
            _staging_residue(self.temp_root, second_root.name),
            (),
        )

        nonempty = self.temp_root / "e2e06-nonempty"
        nonempty.mkdir()
        marker = nonempty / "marker.txt"
        marker.write_text("preserve", encoding="utf-8")
        with (
            patch(
                "trip_decider.e2e_demo.run_wu2_recovery",
                wraps=real_recovery,
                create=True,
            ) as recovery_mock,
            patch(
                "trip_decider.e2e_demo.run_evidence_runtime",
                wraps=real_evidence,
                create=True,
            ) as evidence_mock,
            patch(
                "trip_decider.e2e_demo.run_coarse_planner",
                wraps=real_planner,
                create=True,
            ) as planner_mock,
        ):
            rejected = run_e2e_demo(ANCHOR, first_planning, nonempty)
        self.assertIsNone(rejected.value)
        self.assertEqual(
            rejected.problems[0].error_code,
            "E2E_OUTPUT_ROOT_INVALID",
        )
        self.assertEqual(recovery_mock.call_count, 0)
        self.assertEqual(evidence_mock.call_count, 0)
        self.assertEqual(planner_mock.call_count, 0)
        self.assertEqual(marker.read_text(encoding="utf-8"), "preserve")

        failed_root = self.temp_root / "e2e06-failed-output"
        forced_problem = ValidationProblem(
            error_code="EVIDENCE_RUNTIME_INPUT_INVALID",
            artifact_path="input/forced",
            json_pointer="/forced",
            schema_rule="injected",
            expected="accepted evidence input",
            actual_type="injected",
            message="Evidence Runtime input is invalid.",
        )
        with (
            patch(
                "trip_decider.e2e_demo.run_wu2_recovery",
                wraps=real_recovery,
                create=True,
            ) as recovery_mock,
            patch(
                "trip_decider.e2e_demo.run_evidence_runtime",
                return_value=ValidationResult(None, (forced_problem,)),
                create=True,
            ) as evidence_mock,
            patch(
                "trip_decider.e2e_demo.run_coarse_planner",
                wraps=real_planner,
                create=True,
            ) as planner_mock,
            patch(
                "trip_decider.e2e_demo._render_html",
                wraps=real_render,
                create=True,
            ) as render_mock,
        ):
            failed = run_e2e_demo(
                ANCHOR,
                first_planning,
                failed_root,
            )
        self.assertIsNone(failed.value)
        self.assertEqual(failed.problems, (forced_problem,))
        self.assertEqual(recovery_mock.call_count, 1)
        self.assertEqual(evidence_mock.call_count, 1)
        self.assertEqual(planner_mock.call_count, 0)
        self.assertEqual(render_mock.call_count, 0)
        self.assertFalse(failed_root.exists())
        self.assertEqual(
            _staging_residue(self.temp_root, failed_root.name),
            (),
        )


if __name__ == "__main__":
    unittest.main()
