"""WU2R Resume integration contract cases.

Source: synthetic deterministic OSM-shaped inputs authored from the approved
WU2R Resume Plan v0.1. Expected hashes, provider IDs, candidate IDs, seed
states, and failure classifications are handwritten from the frozen
specification; they are not generated by the interfaces under test.

Coverage: explicit acquisition/FER linkage, failure composition,
multi-identity candidate retention, coverage rejection, order independence,
and offline replay.

Non-coverage: live OSM correctness or completeness, HTTP/retry behavior,
real-place identity, route acquisition, evidence rating, recommendation,
feasibility, planning, or UI.
"""

from __future__ import annotations

import copy
import hashlib
import json
import socket
import tempfile
import unittest
from pathlib import Path
from unittest.mock import Mock, patch

from trip_decider.acquisition_evidence import (
    ACQUISITION_RESPONSE_FAILURE,
    ACQUISITION_TRANSPORT_FAILURE,
    AttemptObservation,
    CleanupItemObservation,
    ResponsePhaseObservation,
    RunnerObservation,
)
from trip_decider.adapters import IngestionContext
from trip_decider.resume_acquisition import (
    ResumeCaptureObservation,
    ResumeSnapshotMetadata,
    replay_wu2r_resume_anchor,
    run_wu2r_resume_acquisition,
)


NOW = "2026-07-28T16:30:00+08:00"
RUN_ID = "run_wu2r_resume_001"
ATTEMPT_GROUP_ID = "WU2R-resume-001"
QUERY_BYTES = b"[out:json];synthetic-wu2r-resume;"
REQUEST_BYTES = b"data=%5Bout%3Ajson%5D%3Bsynthetic-wu2r-resume%3B"
QUERY_SHA256 = hashlib.sha256(QUERY_BYTES).hexdigest()
REQUEST_SHA256 = hashlib.sha256(REQUEST_BYTES).hexdigest()
REQUEST_ID = "urn:uuid:00000001-0000-4000-8000-000000000001"
SEEDS = ("篁岭", "江岭", "李坑", "庆源")

HUANGLING_ATTRACTION = "candidate_8f330e07-0839-4696-8769-19ef50625ec0"
HUANGLING_HAMLET = "candidate_2bd4a053-014f-4e14-8e54-79501b37a671"
JIANGLING = "candidate_7dff94ab-4ca4-40ce-b9c7-33750c519679"
LIKENG = "candidate_b6b13e35-55b6-4099-a30b-7027c684a1c5"


def open_policy() -> dict[str, object]:
    return {
        "source_class": "open_data",
        "capture_mode": "persistent_anchor",
        "storage_policy": "persistent_allowed",
        "replay_allowed": True,
        "fixture_allowed": True,
        "policy_checked_at": NOW,
        "terms_url": "https://www.openstreetmap.org/copyright",
        "authorization_ref": None,
        "license": {
            "identifier": "ODbL-1.0",
            "url": "https://opendatacommons.org/licenses/odbl/1-0/",
            "attribution": "© OpenStreetMap contributors",
        },
    }


def context() -> IngestionContext:
    return IngestionContext(
        request_ref={
            "artifact_id": REQUEST_ID,
            "artifact_type": "request",
            "payload_sha256": "a" * 64,
            "schema_version": "0.1.0",
        },
        run_id=RUN_ID,
        created_at=NOW,
    )


def metadata() -> ResumeSnapshotMetadata:
    return ResumeSnapshotMetadata(
        format_version="0.1.0",
        provider="osm",
        operation="overpass-poi-snapshot",
        crs="WGS84",
        retrieved_at=NOW,
        request_fingerprint=REQUEST_SHA256,
        response_locator={
            "kind": "response_location",
            "value": "synthetic-wu2r-resume.json",
        },
        data_policy=open_policy(),
    )


def element(
    *,
    element_type: str,
    element_id: int,
    name: str,
    category_key: str,
    category_value: str,
) -> dict[str, object]:
    item: dict[str, object] = {
        "type": element_type,
        "id": element_id,
        "tags": {
            "name": name,
            category_key: category_value,
        },
    }
    if element_type == "node":
        item["lat"] = 29.10 + element_id / 100000
        item["lon"] = 117.20 + element_id / 100000
    else:
        item["center"] = {
            "lat": 29.30 + element_id / 100000,
            "lon": 117.40 + element_id / 100000,
        }
    return item


def candidate_elements() -> list[dict[str, object]]:
    return [
        element(
            element_type="node",
            element_id=101,
            name="篁岭",
            category_key="tourism",
            category_value="attraction",
        ),
        element(
            element_type="node",
            element_id=102,
            name="篁岭",
            category_key="place",
            category_value="hamlet",
        ),
        element(
            element_type="relation",
            element_id=103,
            name="江岭",
            category_key="place",
            category_value="hamlet",
        ),
        element(
            element_type="node",
            element_id=104,
            name="李坑",
            category_key="place",
            category_value="village",
        ),
    ]


def raw_response(
    selected: list[dict[str, object]] | None = None,
) -> bytes:
    return json.dumps(
        {
            "version": 0.6,
            "generator": "Overpass API",
            "osm3s": {"timestamp_osm_base": "2026-07-28T00:00:00Z"},
            "elements": (
                copy.deepcopy(selected)
                if selected is not None
                else candidate_elements()
            ),
        },
        ensure_ascii=False,
        sort_keys=True,
        separators=(",", ":"),
    ).encode("utf-8")


def successful_capture(
    response: bytes,
    *,
    selected_metadata: ResumeSnapshotMetadata | None = None,
) -> ResumeCaptureObservation:
    return ResumeCaptureObservation(
        runner_observation=RunnerObservation(
            attempts=(
                AttemptObservation(
                    attempt_id="attempt-0001",
                    request_sha256=REQUEST_SHA256,
                    started_at=NOW,
                    completed_at=NOW,
                    status="succeeded",
                    http_status=200,
                    response_bytes=len(response),
                    response_sha256=hashlib.sha256(response).hexdigest(),
                    content_type="application/json",
                    retry_decision="not_applicable",
                ),
            ),
            retries=(),
            response_phase=ResponsePhaseObservation(
                status="not_evaluated",
                failure_kind=None,
            ),
        ),
        response_bytes=response,
        snapshot_metadata=selected_metadata or metadata(),
    )


def failed_capture() -> ResumeCaptureObservation:
    return ResumeCaptureObservation(
        runner_observation=RunnerObservation(
            attempts=(
                AttemptObservation(
                    attempt_id="attempt-0001",
                    request_sha256=REQUEST_SHA256,
                    started_at=NOW,
                    completed_at=NOW,
                    status="transport_failure",
                    http_status=None,
                    response_bytes=None,
                    response_sha256=None,
                    content_type=None,
                    retry_decision="retry_exhausted",
                ),
            ),
            retries=(),
            response_phase=ResponsePhaseObservation(
                status="not_evaluated",
                failure_kind=None,
            ),
        ),
        response_bytes=None,
        snapshot_metadata=None,
    )


class ResumeIntegrationCase(unittest.TestCase):
    maxDiff = None

    def acquire(
        self,
        capture_result: ResumeCaptureObservation,
        *,
        seeds: tuple[str, ...] = SEEDS,
    ):
        with tempfile.TemporaryDirectory(
            prefix="trip-decider-wu2r-resume-test-"
        ) as raw:
            root = Path(raw)
            primary = root / "runtime" / "failure-evidence.json"
            emergency = root / "emergency" / "failure-evidence.json"
            primary.parent.mkdir()
            emergency.parent.mkdir()
            capture = Mock(return_value=capture_result)
            cleanup = Mock(
                return_value=(
                    CleanupItemObservation(
                        resource_kind="synthetic_capture",
                        existed_before=False,
                        deletion_attempted=False,
                        status="not_present",
                        residue_count=0,
                    ),
                )
            )
            with patch.object(
                socket,
                "create_connection",
                side_effect=AssertionError("network forbidden"),
            ) as network:
                result = run_wu2r_resume_acquisition(
                    run_id=RUN_ID,
                    attempt_group_id=ATTEMPT_GROUP_ID,
                    purpose="wu2r-resume-synthetic",
                    query_bytes=QUERY_BYTES,
                    request_bytes=REQUEST_BYTES,
                    expected_query_sha256=QUERY_SHA256,
                    expected_request_sha256=REQUEST_SHA256,
                    failure_evidence_path=primary,
                    emergency_evidence_path=emergency,
                    capture=capture,
                    cleanup=cleanup,
                    clock=lambda: NOW,
                    seeds=seeds,
                    context=context(),
                )
            persisted = (
                json.loads(primary.read_text(encoding="utf-8"))
                if primary.is_file()
                else None
            )
            return result, persisted, capture.call_count, network.call_count

    def replay(
        self,
        response: bytes,
    ):
        with patch.object(
            socket,
            "create_connection",
            side_effect=AssertionError("network forbidden"),
        ) as network:
            result = replay_wu2r_resume_anchor(
                run_id=RUN_ID,
                query_bytes=QUERY_BYTES,
                request_bytes=REQUEST_BYTES,
                expected_query_sha256=QUERY_SHA256,
                expected_request_sha256=REQUEST_SHA256,
                response_bytes=response,
                expected_response_sha256=hashlib.sha256(response).hexdigest(),
                snapshot_metadata=metadata(),
                seeds=SEEDS,
                context=context(),
            )
        return result, network.call_count

    def test_ri01_explicit_linkage_is_preserved(self) -> None:
        response = raw_response()
        result, persisted, capture_calls, network_calls = self.acquire(
            successful_capture(response)
        )

        self.assertEqual(result.run_id, RUN_ID)
        self.assertEqual(result.attempt_group_id, ATTEMPT_GROUP_ID)
        self.assertEqual(result.query_sha256, QUERY_SHA256)
        self.assertEqual(result.request_sha256, REQUEST_SHA256)
        self.assertEqual(
            result.failure_evidence_path.name,
            "failure-evidence.json",
        )
        self.assertEqual(persisted, result.evidence.document)
        self.assertEqual(capture_calls, 1)
        self.assertEqual(network_calls, 0)

    def test_ri02_terminal_capture_failure_has_evidence_only(self) -> None:
        result, persisted, capture_calls, network_calls = self.acquire(
            failed_capture()
        )

        self.assertTrue(result.evidence.durable_evidence)
        self.assertEqual(result.evidence.document["status"], "failed")
        self.assertEqual(
            result.evidence.document["terminal_failure_code"],
            ACQUISITION_TRANSPORT_FAILURE,
        )
        self.assertIsNone(result.candidate_result)
        self.assertIsNone(result.eligible_response_bytes)
        self.assertEqual(persisted, result.evidence.document)
        self.assertEqual(capture_calls, 1)
        self.assertEqual(network_calls, 0)

    def test_ri03_success_retains_identities_and_three_states(self) -> None:
        response = raw_response()
        result, persisted, capture_calls, network_calls = self.acquire(
            successful_capture(response)
        )

        self.assertEqual(result.evidence.document["status"], "succeeded")
        self.assertIsNotNone(result.candidate_result)
        self.assertEqual(result.eligible_response_bytes, response)
        candidates = result.candidate_result.candidate_artifact["payload"][
            "candidates"
        ]
        self.assertEqual(
            [item["candidate_id"] for item in candidates],
            [
                HUANGLING_ATTRACTION,
                HUANGLING_HAMLET,
                LIKENG,
                JIANGLING,
            ],
        )
        self.assertEqual(
            [
                (item.seed, item.status, item.candidate_refs)
                for item in result.candidate_result.seed_matches
            ],
            [
                (
                    "篁岭",
                    "ambiguous",
                    (HUANGLING_HAMLET, HUANGLING_ATTRACTION),
                ),
                ("江岭", "matched", (JIANGLING,)),
                ("李坑", "matched", (LIKENG,)),
                ("庆源", "unmatched", ()),
            ],
        )
        self.assertEqual(persisted, result.evidence.document)
        self.assertEqual(capture_calls, 1)
        self.assertEqual(network_calls, 0)

    def test_ri04_coverage_rejection_has_no_eligible_raw(self) -> None:
        response = raw_response(candidate_elements()[:2])
        result, persisted, capture_calls, network_calls = self.acquire(
            successful_capture(response),
            seeds=("篁岭", "庆源"),
        )

        self.assertEqual(result.evidence.document["status"], "failed")
        self.assertEqual(
            result.evidence.document["terminal_failure_code"],
            ACQUISITION_RESPONSE_FAILURE,
        )
        self.assertEqual(
            result.evidence.document["response_phase"]["status"],
            "rejected",
        )
        self.assertIsNone(result.candidate_result)
        self.assertIsNone(result.eligible_response_bytes)
        self.assertTrue(result.problems)
        self.assertEqual(persisted, result.evidence.document)
        self.assertEqual(capture_calls, 1)
        self.assertEqual(network_calls, 0)

    def test_ri05_response_order_is_output_independent(self) -> None:
        first, first_network = self.replay(raw_response())
        second, second_network = self.replay(
            raw_response(list(reversed(candidate_elements())))
        )

        self.assertEqual(
            first.candidate_result.candidate_artifact,
            second.candidate_result.candidate_artifact,
        )
        self.assertEqual(
            first.candidate_result.seed_matches,
            second.candidate_result.seed_matches,
        )
        self.assertEqual(
            first.candidate_result.record_local_facts,
            second.candidate_result.record_local_facts,
        )
        self.assertEqual(first_network, 0)
        self.assertEqual(second_network, 0)

    def test_ri06_committed_byte_replay_is_offline(self) -> None:
        response = raw_response()
        result, network_calls = self.replay(response)

        self.assertEqual(result.run_id, RUN_ID)
        self.assertEqual(result.response_sha256, hashlib.sha256(response).hexdigest())
        self.assertEqual(result.response_bytes, len(response))
        self.assertEqual(result.network_attempts, 0)
        self.assertFalse(result.problems)
        self.assertEqual(network_calls, 0)


if __name__ == "__main__":
    unittest.main()
