"""WU2R-FER deterministic failure-evidence contract cases.

Source: ten synthetic injected outcomes authored from the approved WU2R-FER
Plan v0.1.  Expected hashes, codes, retry relations, sink states, and cleanup
fields are handwritten from that specification; they are not generated by
the function under test.

Coverage: ledger-first ordering, closed failure classification, retry
relations, primary/emergency persistence, cleanup evidence, redaction, and
atomic-file cleanup.

Non-coverage: network behavior, provider correctness, real OSM identity,
adapters, candidates, anchors, fixtures, planning, or WU2R replay.
"""

from __future__ import annotations

import io
import json
import socket
import tempfile
import unittest
from contextlib import redirect_stderr, redirect_stdout
from pathlib import Path
from unittest.mock import Mock, patch

from trip_decider.acquisition_evidence import (
    ACQUISITION_CLEANUP_FAILURE,
    ACQUISITION_HTTP_FAILURE,
    ACQUISITION_INTERNAL_FAILURE,
    ACQUISITION_LEDGER_FAILURE,
    ACQUISITION_RESPONSE_FAILURE,
    ACQUISITION_TRANSPORT_FAILURE,
    AttemptObservation,
    CleanupItemObservation,
    ResponsePhaseObservation,
    RetryObservation,
    RunnerObservation,
    run_failure_evidenced_acquisition,
)


REQUEST_BYTES = b"data=approved-query"
REQUEST_SHA256 = (
    "0e0298469c9316cbfab084e4813f479631c96d3ca6cecde9fa0bc06cc5e2f7ee"
)
INVALID_JSON_SHA256 = (
    "f1dec6e9ee608550bd1c39ff2b90134059bac5d02e4e78f6410aed2fbd870bd0"
)
NOW = "2026-07-28T12:00:00+08:00"


def attempt(
    *,
    attempt_id: str = "attempt-0001",
    status: str,
    http_status: int | None = None,
    response_bytes: int | None = None,
    response_sha256: str | None = None,
    content_type: str | None = None,
    retry_decision: str,
) -> AttemptObservation:
    return AttemptObservation(
        attempt_id=attempt_id,
        request_sha256=REQUEST_SHA256,
        started_at=NOW,
        completed_at=NOW,
        status=status,
        http_status=http_status,
        response_bytes=response_bytes,
        response_sha256=response_sha256,
        content_type=content_type,
        retry_decision=retry_decision,
    )


def runner_result(
    *attempts: AttemptObservation,
    retries: tuple[RetryObservation, ...] = (),
    response_status: str = "not_evaluated",
    failure_kind: str | None = None,
) -> RunnerObservation:
    return RunnerObservation(
        attempts=attempts,
        retries=retries,
        response_phase=ResponsePhaseObservation(
            status=response_status,
            failure_kind=failure_kind,
        ),
    )


class FailureEvidenceCase(unittest.TestCase):
    maxDiff = None

    def execute(
        self,
        *,
        runner: Mock,
        cleanup: Mock | None = None,
        primary_persist=None,
        emergency_persist=None,
    ):
        cleanup_effect = cleanup or Mock(return_value=())
        standard_output = io.StringIO()
        error_output = io.StringIO()
        with tempfile.TemporaryDirectory(prefix="trip-decider-fer-test-") as raw:
            root = Path(raw)
            primary = root / "runtime" / "failure-evidence.json"
            emergency = root / "emergency" / "failure-evidence.json"
            primary.parent.mkdir()
            emergency.parent.mkdir()
            with (
                patch.object(
                    socket,
                    "create_connection",
                    side_effect=AssertionError("network forbidden"),
                ) as network,
                redirect_stdout(standard_output),
                redirect_stderr(error_output),
            ):
                result = run_failure_evidenced_acquisition(
                    run_id="run_00000001-0000-4000-8000-000000000001",
                    purpose="wu2r-fer-test",
                    request_bytes=REQUEST_BYTES,
                    primary_path=primary,
                    emergency_path=emergency,
                    runner=runner,
                    cleanup=cleanup_effect,
                    clock=lambda: NOW,
                    primary_persist=primary_persist,
                    emergency_persist=emergency_persist,
                )
            primary_document = (
                json.loads(primary.read_text(encoding="utf-8"))
                if primary.is_file()
                else None
            )
            emergency_document = (
                json.loads(emergency.read_text(encoding="utf-8"))
                if emergency.is_file()
                else None
            )
            atomic_residue = sorted(root.rglob("*.tmp"))
            return (
                result,
                primary_document,
                emergency_document,
                runner.call_count,
                cleanup_effect.call_count,
                network.call_count,
                atomic_residue,
                standard_output.getvalue(),
                error_output.getvalue(),
            )

    def test_fe01_transport_timeout_retry_relation_is_preserved(self) -> None:
        retry = RetryObservation(
            original_attempt_id="attempt-0001",
            retry_attempt_id="attempt-0002",
            same_request_sha256=True,
            retry_reason="transport_failure",
        )
        runner = Mock(
            return_value=runner_result(
                attempt(
                    status="transport_failure",
                    retry_decision="retry_scheduled",
                ),
                attempt(
                    attempt_id="attempt-0002",
                    status="succeeded",
                    http_status=200,
                    response_bytes=2,
                    response_sha256=(
                        "44136fa355b3678a1146ad16f7e8649e94fb4fc21fe77e8310c"
                        "060f61caaff8a"
                    ),
                    content_type="application/json",
                    retry_decision="not_applicable",
                ),
                retries=(retry,),
                response_status="accepted",
            )
        )
        result, primary, _, runner_calls, _, network_calls, *_ = self.execute(
            runner=runner
        )

        self.assertEqual(result.document["status"], "succeeded")
        self.assertIsNone(result.document["terminal_failure_code"])
        self.assertEqual(
            result.document["failure_codes"],
            [ACQUISITION_TRANSPORT_FAILURE],
        )
        self.assertEqual(len(result.document["attempts"]), 2)
        self.assertEqual(
            [item["request_sha256"] for item in result.document["attempts"]],
            [REQUEST_SHA256, REQUEST_SHA256],
        )
        self.assertEqual(
            result.document["retries"],
            [
                {
                    "original_attempt_id": "attempt-0001",
                    "retry_attempt_id": "attempt-0002",
                    "same_request_sha256": True,
                    "retry_reason": "transport_failure",
                }
            ],
        )
        self.assertEqual(primary, result.document)
        self.assertEqual(runner_calls, 1)
        self.assertEqual(network_calls, 0)

    def test_fe02_http_400_is_complete_and_not_retried(self) -> None:
        runner = Mock(
            return_value=runner_result(
                attempt(
                    status="http_response_failure",
                    http_status=400,
                    response_bytes=0,
                    response_sha256=(
                        "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495"
                        "991b7852b855"
                    ),
                    content_type="application/json",
                    retry_decision="not_retryable_http",
                )
            )
        )
        result, primary, _, runner_calls, _, network_calls, *_ = self.execute(
            runner=runner
        )

        self.assertEqual(result.document["status"], "failed")
        self.assertEqual(
            result.document["terminal_failure_code"],
            ACQUISITION_HTTP_FAILURE,
        )
        self.assertEqual(result.document["failure_codes"], [ACQUISITION_HTTP_FAILURE])
        self.assertEqual(result.document["attempts"][0]["http_status"], 400)
        self.assertEqual(result.document["retries"], [])
        self.assertEqual(primary, result.document)
        self.assertEqual(runner_calls, 1)
        self.assertEqual(network_calls, 0)

    def test_fe03_invalid_json_retains_response_metadata(self) -> None:
        runner = Mock(
            return_value=runner_result(
                attempt(
                    status="succeeded",
                    http_status=200,
                    response_bytes=9,
                    response_sha256=INVALID_JSON_SHA256,
                    content_type="application/json",
                    retry_decision="not_applicable",
                ),
                response_status="rejected",
                failure_kind="invalid_json",
            )
        )
        result, primary, _, runner_calls, _, network_calls, *_ = self.execute(
            runner=runner
        )

        self.assertEqual(result.document["status"], "failed")
        self.assertEqual(
            result.document["terminal_failure_code"],
            ACQUISITION_RESPONSE_FAILURE,
        )
        self.assertEqual(
            result.document["failure_codes"],
            [ACQUISITION_RESPONSE_FAILURE],
        )
        observed = result.document["attempts"][0]
        self.assertEqual(observed["response_bytes"], 9)
        self.assertEqual(observed["response_sha256"], INVALID_JSON_SHA256)
        self.assertNotIn("response_body", observed)
        self.assertEqual(
            result.document["response_phase"],
            {"status": "rejected", "failure_kind": "invalid_json"},
        )
        self.assertEqual(primary, result.document)
        self.assertEqual(runner_calls, 1)
        self.assertEqual(network_calls, 0)

    def test_fe04_internal_exception_has_sanitized_terminal_attempt(self) -> None:
        runner = Mock(side_effect=RuntimeError("secret-value from dependency"))
        result, primary, _, runner_calls, _, network_calls, *_ = self.execute(
            runner=runner
        )

        self.assertEqual(result.document["status"], "failed")
        self.assertEqual(
            result.document["terminal_failure_code"],
            ACQUISITION_INTERNAL_FAILURE,
        )
        self.assertEqual(
            result.document["failure_codes"],
            [ACQUISITION_INTERNAL_FAILURE],
        )
        self.assertEqual(len(result.document["attempts"]), 1)
        self.assertEqual(result.document["attempts"][0]["status"], "internal_failure")
        serialized = json.dumps(result.document, ensure_ascii=False)
        self.assertNotIn("secret-value", serialized)
        self.assertNotIn("RuntimeError", serialized)
        self.assertEqual(primary, result.document)
        self.assertEqual(runner_calls, 1)
        self.assertEqual(network_calls, 0)

    def test_fe05_started_primary_failure_uses_explicit_emergency_sink(self) -> None:
        def fail_primary(_path: Path, _payload: bytes) -> None:
            raise OSError("private primary failure")

        runner = Mock(
            return_value=runner_result(
                attempt(status="succeeded", retry_decision="not_applicable"),
                response_status="accepted",
            )
        )
        (
            result,
            primary,
            emergency,
            runner_calls,
            cleanup_calls,
            network_calls,
            *_,
        ) = self.execute(runner=runner, primary_persist=fail_primary)

        self.assertEqual(result.document["status"], "evidence_persistence_failed")
        self.assertEqual(
            result.document["terminal_failure_code"],
            ACQUISITION_LEDGER_FAILURE,
        )
        self.assertEqual(result.document["failure_codes"], [ACQUISITION_LEDGER_FAILURE])
        self.assertEqual(result.document["attempts"], [])
        self.assertEqual(result.document["persistence"]["primary_status"], "failed")
        self.assertTrue(result.document["persistence"]["emergency_attempted"])
        self.assertEqual(
            result.document["persistence"]["emergency_status"],
            "succeeded",
        )
        self.assertIsNone(primary)
        self.assertEqual(emergency, result.document)
        self.assertTrue(result.durable_evidence)
        self.assertEqual(runner_calls, 0)
        self.assertEqual(cleanup_calls, 0)
        self.assertEqual(network_calls, 0)

    def test_fe06_both_started_sinks_fail_before_runner(self) -> None:
        def fail_sink(_path: Path, _payload: bytes) -> None:
            raise OSError("private sink failure")

        runner = Mock()
        (
            result,
            primary,
            emergency,
            runner_calls,
            cleanup_calls,
            network_calls,
            *_,
        ) = self.execute(
            runner=runner,
            primary_persist=fail_sink,
            emergency_persist=fail_sink,
        )

        self.assertEqual(result.document["status"], "evidence_persistence_failed")
        self.assertEqual(
            result.document["terminal_failure_code"],
            ACQUISITION_LEDGER_FAILURE,
        )
        self.assertEqual(result.document["persistence"]["primary_status"], "failed")
        self.assertEqual(result.document["persistence"]["emergency_status"], "failed")
        self.assertFalse(result.durable_evidence)
        self.assertIsNone(result.evidence_path)
        self.assertIsNone(result.emergency_path)
        self.assertIsNone(primary)
        self.assertIsNone(emergency)
        self.assertEqual(runner_calls, 0)
        self.assertEqual(cleanup_calls, 0)
        self.assertEqual(network_calls, 0)

    def test_fe07_cleanup_failure_preserves_original_failure(self) -> None:
        runner = Mock(
            return_value=runner_result(
                attempt(
                    status="http_response_failure",
                    http_status=500,
                    response_bytes=None,
                    response_sha256=None,
                    content_type=None,
                    retry_decision="not_retryable_http",
                )
            )
        )
        cleanup = Mock(
            return_value=(
                CleanupItemObservation(
                    resource_kind="raw_temp",
                    existed_before=True,
                    deletion_attempted=True,
                    status="failed",
                    residue_count=1,
                ),
            )
        )
        result, primary, _, _, cleanup_calls, network_calls, *_ = self.execute(
            runner=runner,
            cleanup=cleanup,
        )

        self.assertEqual(result.document["status"], "failed")
        self.assertEqual(
            result.document["terminal_failure_code"],
            ACQUISITION_CLEANUP_FAILURE,
        )
        self.assertEqual(
            result.document["failure_codes"],
            [ACQUISITION_HTTP_FAILURE, ACQUISITION_CLEANUP_FAILURE],
        )
        self.assertEqual(result.document["cleanup"]["status"], "failed")
        self.assertEqual(
            result.document["cleanup"]["items"],
            [
                {
                    "resource_kind": "raw_temp",
                    "existed_before": True,
                    "deletion_attempted": True,
                    "status": "failed",
                    "residue_count": 1,
                }
            ],
        )
        self.assertEqual(primary, result.document)
        self.assertEqual(cleanup_calls, 1)
        self.assertEqual(network_calls, 0)

    def test_fe08_transport_retry_exhaustion_is_exact(self) -> None:
        retry = RetryObservation(
            original_attempt_id="attempt-0001",
            retry_attempt_id="attempt-0002",
            same_request_sha256=True,
            retry_reason="transport_failure",
        )
        runner = Mock(
            return_value=runner_result(
                attempt(
                    status="transport_failure",
                    retry_decision="retry_scheduled",
                ),
                attempt(
                    attempt_id="attempt-0002",
                    status="transport_failure",
                    retry_decision="retry_exhausted",
                ),
                retries=(retry,),
            )
        )
        result, primary, _, runner_calls, _, network_calls, *_ = self.execute(
            runner=runner
        )

        self.assertEqual(result.document["status"], "failed")
        self.assertEqual(
            result.document["terminal_failure_code"],
            ACQUISITION_TRANSPORT_FAILURE,
        )
        self.assertEqual(
            result.document["failure_codes"],
            [ACQUISITION_TRANSPORT_FAILURE],
        )
        self.assertEqual(len(result.document["attempts"]), 2)
        self.assertEqual(len(result.document["retries"]), 1)
        self.assertEqual(
            result.document["attempts"][1]["retry_decision"],
            "retry_exhausted",
        )
        self.assertEqual(primary, result.document)
        self.assertEqual(runner_calls, 1)
        self.assertEqual(network_calls, 0)

    def test_fe09_terminal_primary_failure_retains_complete_emergency(self) -> None:
        primary_calls = 0

        def fail_after_started(path: Path, payload: bytes) -> None:
            nonlocal primary_calls
            primary_calls += 1
            if primary_calls > 1:
                raise OSError("private terminal write failure")
            path.write_bytes(payload)

        runner = Mock(
            return_value=runner_result(
                attempt(
                    status="http_response_failure",
                    http_status=503,
                    response_bytes=3,
                    response_sha256=(
                        "2f05d4b689d270cafb02285f35f44866bfe1dc3fc3a887d70e"
                        "ca9320887028d"
                    ),
                    content_type="text/plain",
                    retry_decision="not_retryable_http",
                )
            )
        )
        (
            result,
            primary,
            emergency,
            runner_calls,
            _,
            network_calls,
            *_,
        ) = self.execute(runner=runner, primary_persist=fail_after_started)

        self.assertEqual(primary_calls, 2)
        self.assertEqual(
            result.document["terminal_failure_code"],
            ACQUISITION_LEDGER_FAILURE,
        )
        self.assertEqual(
            result.document["failure_codes"],
            [ACQUISITION_HTTP_FAILURE, ACQUISITION_LEDGER_FAILURE],
        )
        self.assertEqual(result.document["attempts"][0]["http_status"], 503)
        self.assertEqual(result.document["persistence"]["primary_status"], "failed")
        self.assertEqual(
            result.document["persistence"]["emergency_status"],
            "succeeded",
        )
        self.assertEqual(primary["status"], "started")
        self.assertEqual(emergency, result.document)
        self.assertEqual(result.emergency_path.name, "failure-evidence.json")
        self.assertTrue(result.durable_evidence)
        self.assertEqual(runner_calls, 1)
        self.assertEqual(network_calls, 0)

    def test_fe10_clean_success_is_atomic_silent_and_reloadable(self) -> None:
        runner = Mock(
            return_value=runner_result(
                attempt(
                    status="succeeded",
                    http_status=200,
                    response_bytes=2,
                    response_sha256=(
                        "44136fa355b3678a1146ad16f7e8649e94fb4fc21fe77e8310c"
                        "060f61caaff8a"
                    ),
                    content_type="application/json",
                    retry_decision="not_applicable",
                ),
                response_status="accepted",
            )
        )
        cleanup = Mock(
            return_value=(
                CleanupItemObservation(
                    resource_kind="raw_temp",
                    existed_before=True,
                    deletion_attempted=True,
                    status="removed",
                    residue_count=0,
                ),
                CleanupItemObservation(
                    resource_kind="atomic_temp",
                    existed_before=False,
                    deletion_attempted=False,
                    status="not_present",
                    residue_count=0,
                ),
            )
        )
        (
            result,
            primary,
            emergency,
            runner_calls,
            cleanup_calls,
            network_calls,
            atomic_residue,
            standard_output,
            error_output,
        ) = self.execute(runner=runner, cleanup=cleanup)

        self.assertEqual(result.document["status"], "succeeded")
        self.assertIsNone(result.document["terminal_failure_code"])
        self.assertEqual(result.document["failure_codes"], [])
        self.assertEqual(result.document["request_sha256"], REQUEST_SHA256)
        self.assertEqual(result.document["cleanup"]["status"], "succeeded")
        self.assertEqual(primary, result.document)
        self.assertIsNone(emergency)
        self.assertEqual(result.evidence_path.name, "failure-evidence.json")
        self.assertIsNone(result.emergency_path)
        self.assertTrue(result.durable_evidence)
        self.assertEqual(atomic_residue, [])
        self.assertEqual(standard_output, "")
        self.assertEqual(error_output, "")
        self.assertEqual(runner_calls, 1)
        self.assertEqual(cleanup_calls, 1)
        self.assertEqual(network_calls, 0)


if __name__ == "__main__":
    unittest.main()
