"""WU2 Recovery deterministic contract cases.

Source: synthetic deterministic OSM-shaped mappings written from WU2R Plan
v0.1.  Expected candidate IDs and fields are handwritten from the frozen
provider-identity and stable-ID specifications; they are not generated by
the Recovery functions under test.

Coverage: plural provider identities, exact seed accounting, candidate-local
source facts, and pre-route identity guarding.

Non-coverage: live OSM/Overpass data, real-place identity, OSM completeness,
route acquisition, evidence rating, recommendation, feasibility, or planning.
"""

from __future__ import annotations

import copy
import socket
import unittest
from unittest.mock import patch

from trip_decider.adapters import IngestionContext, normalize_open_data_pois
from trip_decider.recovery import (
    RecoveryCandidateResult,
    SeedMatch,
    ingest_candidate_pool,
    prepare_route_endpoints,
)


CHECKED_AT = "2026-07-28T00:00:00+08:00"
RETRIEVED_AT = "2026-07-28T08:00:00+08:00"
REQUEST_ID = "urn:uuid:00000001-0000-4000-8000-000000000001"

HUANGLING_ATTRACTION = "candidate_8f330e07-0839-4696-8769-19ef50625ec0"
HUANGLING_HAMLET = "candidate_2bd4a053-014f-4e14-8e54-79501b37a671"
JIANGLING = "candidate_7dff94ab-4ca4-40ce-b9c7-33750c519679"
LIKENG = "candidate_b6b13e35-55b6-4099-a30b-7027c684a1c5"


def open_policy() -> dict[str, object]:
    return {
        "source_class": "open_data",
        "capture_mode": "persistent_anchor",
        "storage_policy": "persistent_allowed",
        "replay_allowed": True,
        "fixture_allowed": True,
        "policy_checked_at": CHECKED_AT,
        "terms_url": "https://www.openstreetmap.org/copyright",
        "authorization_ref": None,
        "license": {
            "identifier": "ODbL-1.0",
            "url": "https://opendatacommons.org/licenses/odbl/1-0/",
            "attribution": "© OpenStreetMap contributors",
        },
    }


def context() -> IngestionContext:
    return IngestionContext(
        request_ref={
            "artifact_id": REQUEST_ID,
            "artifact_type": "request",
            "payload_sha256": "a" * 64,
            "schema_version": "0.1.0",
        },
        run_id="run_00000001-0000-4000-8000-000000000001",
        created_at=RETRIEVED_AT,
    )


def element(
    *,
    element_type: str,
    element_id: int,
    name: str,
    category_key: str,
    category_value: str,
) -> dict[str, object]:
    item: dict[str, object] = {
        "type": element_type,
        "id": element_id,
        "tags": {
            "name": name,
            category_key: category_value,
        },
    }
    if element_type == "node":
        item["lat"] = 29.10 + element_id / 100000
        item["lon"] = 117.20 + element_id / 100000
    else:
        item["center"] = {
            "lat": 29.30 + element_id / 100000,
            "lon": 117.40 + element_id / 100000,
        }
    return item


def candidate_elements() -> list[dict[str, object]]:
    return [
        element(
            element_type="node",
            element_id=101,
            name="篁岭",
            category_key="tourism",
            category_value="attraction",
        ),
        element(
            element_type="node",
            element_id=102,
            name="篁岭",
            category_key="place",
            category_value="hamlet",
        ),
        element(
            element_type="relation",
            element_id=103,
            name="江岭",
            category_key="place",
            category_value="hamlet",
        ),
        element(
            element_type="node",
            element_id=104,
            name="李坑",
            category_key="place",
            category_value="village",
        ),
    ]


def snapshot(
    selected: list[dict[str, object]] | None = None,
) -> dict[str, object]:
    return {
        "format_version": "0.1.0",
        "provider": "osm",
        "operation": "overpass-poi-snapshot",
        "crs": "WGS84",
        "retrieved_at": RETRIEVED_AT,
        "request_fingerprint": "b" * 64,
        "response_locator": {
            "kind": "response_location",
            "value": "synthetic-wu2r-pois.json",
        },
        "data_policy": open_policy(),
        "result": {
            "status": "success",
            "document": {
                "version": 0.6,
                "generator": "Overpass API",
                "osm3s": {"timestamp_osm_base": "2026-07-28T00:00:00Z"},
                "elements": (
                    copy.deepcopy(selected)
                    if selected is not None
                    else candidate_elements()
                ),
            },
        },
    }


SEEDS = ("篁岭", "江岭", "李坑", "庆源")


class RecoveryContractCase(unittest.TestCase):
    maxDiff = None

    def ingest(
        self,
        *,
        selected: list[dict[str, object]] | None = None,
        seeds: tuple[object, ...] = SEEDS,
    ):
        with patch.object(
            socket,
            "create_connection",
            side_effect=AssertionError("network forbidden"),
        ):
            return ingest_candidate_pool(snapshot(selected), seeds, context())

    def valid_result(self) -> RecoveryCandidateResult:
        result = self.ingest()
        self.assertEqual(result.problems, ())
        self.assertIsNotNone(result.value)
        return result.value

    def assert_problem(
        self,
        result: object,
        code: str,
        pointer: str,
        rule: str,
    ) -> None:
        problems = getattr(result, "problems")
        self.assertEqual(len(problems), 1)
        self.assertEqual(problems[0].error_code, code)
        self.assertEqual(problems[0].json_pointer, pointer)
        self.assertEqual(problems[0].schema_rule, rule)

    def test_mi01_every_provider_identity_remains_distinct(self) -> None:
        value = self.valid_result()
        candidates = value.candidate_artifact["payload"]["candidates"]
        self.assertEqual(len(candidates), 4)
        self.assertEqual(
            [
                (
                    item["provider"]["name"],
                    item["provider"]["record_type"],
                    item["provider"]["record_id"],
                )
                for item in candidates
            ],
            [
                ("osm", "node", "101"),
                ("osm", "node", "102"),
                ("osm", "node", "104"),
                ("osm", "relation", "103"),
            ],
        )
        self.assertEqual(len({item["candidate_id"] for item in candidates}), 4)

    def test_mi02_same_label_is_ambiguous_with_all_refs(self) -> None:
        value = self.valid_result()
        match = value.seed_matches[0]
        self.assertEqual(match.seed, "篁岭")
        self.assertEqual(match.status, "ambiguous")
        self.assertEqual(
            match.candidate_refs,
            tuple(sorted((HUANGLING_ATTRACTION, HUANGLING_HAMLET))),
        )

    def test_mi03_one_exact_candidate_is_matched(self) -> None:
        value = self.valid_result()
        match = value.seed_matches[1]
        self.assertEqual(match.seed, "江岭")
        self.assertEqual(match.status, "matched")
        self.assertEqual(match.candidate_refs, (JIANGLING,))

    def test_mi04_no_exact_candidate_is_unmatched(self) -> None:
        value = self.valid_result()
        match = value.seed_matches[3]
        self.assertEqual(match.seed, "庆源")
        self.assertEqual(match.status, "unmatched")
        self.assertEqual(match.candidate_refs, ())

    def test_mi05_response_order_does_not_change_results(self) -> None:
        forward = self.ingest()
        reverse = self.ingest(selected=list(reversed(candidate_elements())))
        self.assertEqual(forward.problems, ())
        self.assertEqual(reverse.problems, ())
        self.assertEqual(
            forward.value.candidate_artifact["payload"],
            reverse.value.candidate_artifact["payload"],
        )
        self.assertEqual(forward.value.seed_matches, reverse.value.seed_matches)
        self.assertEqual(
            forward.value.record_local_facts,
            reverse.value.record_local_facts,
        )

    def test_mi06_category_does_not_rank_or_remove(self) -> None:
        value = self.valid_result()
        candidates = value.candidate_artifact["payload"]["candidates"]
        huangling = [item for item in candidates if item["label"] == "篁岭"]
        self.assertEqual(len(huangling), 2)
        self.assertEqual(
            {
                item["provider"]["categories"][0]["code"]
                for item in huangling
            },
            {"tourism=attraction", "place=hamlet"},
        )
        self.assertEqual(value.seed_matches[0].status, "ambiguous")

    def test_mi07_record_facts_are_candidate_local(self) -> None:
        value = self.valid_result()
        facts = {
            fact.candidate_id: fact for fact in value.record_local_facts
        }
        fact = facts[HUANGLING_HAMLET]
        self.assertEqual(fact.provider_name, "osm")
        self.assertEqual(fact.provider_record_type, "node")
        self.assertEqual(fact.provider_record_id, "102")
        self.assertEqual(fact.categories, (("place=hamlet", "hamlet"),))
        self.assertEqual(fact.location["crs"], "WGS84")
        self.assertEqual(
            fact.source_refs,
            ({"kind": "provider_item", "value": "osm:node:102"},),
        )

    def test_mi08_unmatched_has_no_placeholder_or_rejection(self) -> None:
        value = self.valid_result()
        payload = value.candidate_artifact["payload"]
        self.assertEqual(payload["rejected_inputs"], [])
        self.assertNotIn("庆源", [item["label"] for item in payload["candidates"]])
        self.assertEqual(value.seed_matches[3].candidate_refs, ())

    def test_mi09_duplicate_seed_hard_fails(self) -> None:
        result = self.ingest(seeds=("篁岭", "篁岭"))
        self.assert_problem(
            result,
            "RECOVERY_SEED_INPUT_INVALID",
            "/seeds/1",
            "uniqueSeed",
        )

    def test_mi10_invalid_seed_hard_fails_without_coercion(self) -> None:
        empty = self.ingest(seeds=("",))
        self.assert_problem(
            empty,
            "RECOVERY_SEED_INPUT_INVALID",
            "/seeds/0",
            "seed",
        )
        non_string = self.ingest(seeds=(42,))
        self.assert_problem(
            non_string,
            "RECOVERY_SEED_INPUT_INVALID",
            "/seeds/0",
            "seed",
        )

    def test_mi11_all_accounting_refs_resolve_and_match_label(self) -> None:
        value = self.valid_result()
        candidates = {
            item["candidate_id"]: item
            for item in value.candidate_artifact["payload"]["candidates"]
        }
        self.assertEqual(len(value.seed_matches), len(SEEDS))
        for match in value.seed_matches:
            for candidate_ref in match.candidate_refs:
                self.assertIn(candidate_ref, candidates)
                self.assertEqual(candidates[candidate_ref]["label"], match.seed)

    def route(self, from_seed: str, to_seed: str, value=None):
        selected = value if value is not None else self.route_candidate_result()
        with patch.object(
            socket,
            "create_connection",
            side_effect=AssertionError("network forbidden"),
        ):
            return prepare_route_endpoints(selected, from_seed, to_seed)

    def route_candidate_result(self) -> RecoveryCandidateResult:
        adapter_result = normalize_open_data_pois(snapshot(), context())
        self.assertEqual(adapter_result.problems, ())
        self.assertIsNotNone(adapter_result.value)
        return RecoveryCandidateResult(
            candidate_artifact=adapter_result.value,
            seed_matches=(
                SeedMatch(
                    seed="篁岭",
                    status="ambiguous",
                    candidate_refs=tuple(
                        sorted((HUANGLING_ATTRACTION, HUANGLING_HAMLET))
                    ),
                ),
                SeedMatch(
                    seed="江岭",
                    status="matched",
                    candidate_refs=(JIANGLING,),
                ),
                SeedMatch(
                    seed="李坑",
                    status="matched",
                    candidate_refs=(LIKENG,),
                ),
                SeedMatch(
                    seed="庆源",
                    status="unmatched",
                    candidate_refs=(),
                ),
            ),
            record_local_facts=(),
        )

    def test_rg01_two_matched_seeds_produce_stable_refs(self) -> None:
        result = self.route("江岭", "李坑")
        self.assertEqual(result.problems, ())
        self.assertIsNotNone(result.value)
        self.assertEqual(result.value.from_candidate_ref, JIANGLING)
        self.assertEqual(result.value.to_candidate_ref, LIKENG)

    def test_rg02_ambiguous_origin_blocks_route(self) -> None:
        result = self.route("篁岭", "江岭")
        self.assert_problem(
            result,
            "RECOVERY_ROUTE_ENDPOINT_UNRESOLVED",
            "/from_seed",
            "matchedCandidate",
        )

    def test_rg03_ambiguous_destination_blocks_route(self) -> None:
        result = self.route("江岭", "篁岭")
        self.assert_problem(
            result,
            "RECOVERY_ROUTE_ENDPOINT_UNRESOLVED",
            "/to_seed",
            "matchedCandidate",
        )

    def test_rg04_unmatched_endpoint_blocks_route(self) -> None:
        result = self.route("江岭", "庆源")
        self.assert_problem(
            result,
            "RECOVERY_ROUTE_ENDPOINT_UNRESOLVED",
            "/to_seed",
            "matchedCandidate",
        )

    def test_rg05_inconsistent_reference_blocks_without_lookup(self) -> None:
        valid = self.route_candidate_result()
        corrupt = RecoveryCandidateResult(
            candidate_artifact=valid.candidate_artifact,
            seed_matches=(
                SeedMatch(
                    seed="江岭",
                    status="matched",
                    candidate_refs=(
                        "candidate_ffffffff-ffff-4fff-8fff-ffffffffffff",
                    ),
                ),
                valid.seed_matches[2],
            ),
            record_local_facts=valid.record_local_facts,
        )
        result = self.route("江岭", "李坑", corrupt)
        self.assert_problem(
            result,
            "RECOVERY_CANDIDATE_ARTIFACT_INVALID",
            "/from_seed/candidate_refs/0",
            "candidateReference",
        )


if __name__ == "__main__":
    unittest.main()
