"""WU2R downstream offline Recovery contract cases.

Source: the committed ``jiangxi_multi_identity_smoke`` real anchor and its
independently authored case/replay controls. Expected artifacts, identities,
seed states, facts, counts, paths, and hashes are read from those frozen
controls rather than generated by ``run_wu2_recovery``.

Coverage: exact-path offline replay, four deterministic output documents,
independent Candidate equality, seed/fact accounting, installed-byte hashes,
transactional rejection, and a zero-network boundary.

Non-coverage: live OSM correctness or completeness, acquisition, provider
normalization internals, identity selection, route acquisition, evidence
rating, recommendation, feasibility, planning, or UI.
"""

from __future__ import annotations

import hashlib
import json
import shutil
import socket
import tempfile
import unittest
import urllib.request
from pathlib import Path
from unittest.mock import patch

from trip_decider.recovery import RecoveryRunSummary, run_wu2_recovery
from trip_decider.resume_acquisition import (
    replay_wu2r_resume_anchor as real_replay_function,
)


ROOT = Path(__file__).resolve().parents[1]
REAL_FIXTURE = ROOT / "fixtures" / "jiangxi_multi_identity_smoke"
OUTPUT_FILENAMES = (
    "candidates.json",
    "seed-accounting.json",
    "record-local-facts.json",
    "run-summary.json",
)


def _load_json(path: Path) -> object:
    return json.loads(path.read_text(encoding="utf-8"))


def _fixture_controls(root: Path = REAL_FIXTURE):
    case = _load_json(root / "case.json")
    replay = _load_json(root / "replay.json")
    documents = {
        item["relative_path"]: json.loads(item["content_utf8"])
        for item in case["documents"]
    }
    return case, replay, documents


def _canonical_payload_hash(payload: object) -> str:
    return hashlib.sha256(
        json.dumps(
            payload,
            ensure_ascii=False,
            allow_nan=False,
            sort_keys=True,
            separators=(",", ":"),
        ).encode("utf-8")
    ).hexdigest()


def _file_hash(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def _expected_facts(replay: dict[str, object]) -> list[dict[str, object]]:
    return replay["expected"]["record_local_facts"]


class DownstreamOfflineRecoveryTests(unittest.TestCase):
    maxDiff = None

    def _run(self, replay_root: Path, output_root: Path):
        with (
            patch.object(
                socket,
                "create_connection",
                side_effect=AssertionError("network forbidden"),
            ) as socket_network,
            patch.object(
                urllib.request,
                "urlopen",
                side_effect=AssertionError("network forbidden"),
            ) as url_network,
        ):
            result = run_wu2_recovery(replay_root, output_root)
        return result, socket_network.call_count + url_network.call_count

    def test_dr01_valid_anchor_emits_four_files(self) -> None:
        with tempfile.TemporaryDirectory(prefix="trip-decider-dor-dr01-") as temp:
            output_root = Path(temp) / "output"
            result, network_attempts = self._run(REAL_FIXTURE, output_root)

            self.assertFalse(result.problems)
            self.assertIsInstance(result.value, RecoveryRunSummary)
            self.assertEqual(
                sorted(path.name for path in output_root.iterdir()),
                sorted(OUTPUT_FILENAMES),
            )
            for filename in OUTPUT_FILENAMES:
                raw = (output_root / filename).read_bytes()
                self.assertFalse(raw.startswith(b"\xef\xbb\xbf"))
                self.assertTrue(raw.endswith(b"\n"))
                self.assertIsInstance(
                    json.loads(raw.decode("utf-8", errors="strict")),
                    dict,
                )
            self.assertEqual(
                result.value.candidate_artifact_path,
                output_root / "candidates.json",
            )
            self.assertEqual(
                result.value.seed_accounting_path,
                output_root / "seed-accounting.json",
            )
            self.assertEqual(
                result.value.record_local_facts_path,
                output_root / "record-local-facts.json",
            )
            self.assertEqual(
                result.value.run_summary_path,
                output_root / "run-summary.json",
            )
            self.assertEqual(result.value.candidate_count, 7)
            self.assertEqual(result.value.network_attempts, 0)
            self.assertEqual(network_attempts, 0)

    def test_dr02_candidate_equals_independent_artifact(self) -> None:
        case, replay, documents = _fixture_controls()
        expected = documents["candidates.json"]
        with tempfile.TemporaryDirectory(prefix="trip-decider-dor-dr02-") as temp:
            output_root = Path(temp) / "output"
            result, network_attempts = self._run(REAL_FIXTURE, output_root)
            actual = _load_json(output_root / "candidates.json")

            self.assertFalse(result.problems)
            self.assertEqual(actual, expected)
            self.assertEqual(actual["artifact_id"], case["root_artifact_id"])
            self.assertEqual(
                actual["artifact_id"],
                replay["expected"]["candidate_artifact_id"],
            )
            self.assertEqual(
                _canonical_payload_hash(actual["payload"]),
                replay["expected"]["candidate_payload_sha256"],
            )
            self.assertEqual(
                set(actual),
                {
                    "artifact_id",
                    "artifact_type",
                    "created_at",
                    "integrity",
                    "payload",
                    "producer",
                    "provenance",
                    "schema_version",
                },
            )
            self.assertEqual(
                [
                    (
                        item["provider"]["record_type"],
                        item["provider"]["record_id"],
                    )
                    for item in actual["payload"]["candidates"]
                ],
                [
                    (item["record_type"], item["record_id"])
                    for item in replay["expected"]["provider_identities"]
                ],
            )
            self.assertEqual(len(actual["payload"]["candidates"]), 7)
            self.assertEqual(network_attempts, 0)

    def test_dr03_seed_accounting_equals_replay_expectations(self) -> None:
        _case, replay, documents = _fixture_controls()
        expected_matches = replay["expected"]["seed_matches"]
        candidate_ids = {
            item["candidate_id"]
            for item in documents["candidates.json"]["payload"]["candidates"]
        }
        with tempfile.TemporaryDirectory(prefix="trip-decider-dor-dr03-") as temp:
            output_root = Path(temp) / "output"
            result, network_attempts = self._run(REAL_FIXTURE, output_root)
            accounting = _load_json(output_root / "seed-accounting.json")
            summary = _load_json(output_root / "run-summary.json")

            self.assertFalse(result.problems)
            self.assertEqual(
                accounting,
                {
                    "schema_version": (
                        "wu2r-downstream-seed-accounting/1.0"
                    ),
                    "run_id": replay["run_id"],
                    "seed_matches": expected_matches,
                },
            )
            self.assertEqual(
                [item["seed"] for item in accounting["seed_matches"]],
                [item["seed"] for item in expected_matches],
            )
            self.assertEqual(
                summary["seed_status_counts"],
                {"matched": 2, "ambiguous": 1, "unmatched": 1},
            )
            for item in accounting["seed_matches"]:
                self.assertTrue(
                    set(item["candidate_refs"]).issubset(candidate_ids)
                )
            unmatched = [
                item
                for item in accounting["seed_matches"]
                if item["status"] == "unmatched"
            ]
            self.assertEqual(len(unmatched), 1)
            self.assertEqual(unmatched[0]["candidate_refs"], [])
            self.assertEqual(network_attempts, 0)

    def test_dr04_facts_and_hashes_are_deterministic_across_roots(self) -> None:
        case, replay, _documents = _fixture_controls()
        with tempfile.TemporaryDirectory(prefix="trip-decider-dor-dr04-") as temp:
            first_root = Path(temp) / "first"
            second_root = Path(temp) / "second"
            first, first_network = self._run(REAL_FIXTURE, first_root)
            second, second_network = self._run(REAL_FIXTURE, second_root)
            first_facts = _load_json(first_root / "record-local-facts.json")
            first_summary = _load_json(first_root / "run-summary.json")
            second_summary = _load_json(second_root / "run-summary.json")

            self.assertFalse(first.problems)
            self.assertFalse(second.problems)
            self.assertEqual(
                first_facts,
                {
                    "schema_version": (
                        "wu2r-downstream-record-local-facts/1.0"
                    ),
                    "run_id": replay["run_id"],
                    "record_local_facts": _expected_facts(replay),
                },
            )
            self.assertEqual(
                [
                    item["candidate_id"]
                    for item in first_facts["record_local_facts"]
                ],
                sorted(
                    item["candidate_id"]
                    for item in first_facts["record_local_facts"]
                ),
            )
            for filename in OUTPUT_FILENAMES:
                self.assertEqual(
                    (first_root / filename).read_bytes(),
                    (second_root / filename).read_bytes(),
                )
            self.assertEqual(
                _file_hash(first_root / "run-summary.json"),
                _file_hash(second_root / "run-summary.json"),
            )
            for filename, expected_hash in first_summary[
                "output_sha256"
            ].items():
                self.assertEqual(
                    _file_hash(first_root / filename),
                    expected_hash,
                )
                self.assertEqual(
                    _file_hash(second_root / filename),
                    second_summary["output_sha256"][filename],
                )
            self.assertEqual(
                first_summary["input_fixture_identity"],
                {
                    "case_id": case["case_id"],
                    "case_version": case["case_version"],
                    "root_artifact_id": case["root_artifact_id"],
                    "case_sha256": _file_hash(REAL_FIXTURE / "case.json"),
                    "replay_sha256": _file_hash(
                        REAL_FIXTURE / "replay.json"
                    ),
                    "raw_response_sha256": _file_hash(
                        REAL_FIXTURE / "osm-pois.json"
                    ),
                },
            )
            self.assertEqual(first_summary["completion_status"], "completed")
            self.assertEqual(
                first_summary["output_paths"],
                {
                    "candidate_artifact_path": "candidates.json",
                    "seed_accounting_path": "seed-accounting.json",
                    "record_local_facts_path": "record-local-facts.json",
                    "run_summary_path": "run-summary.json",
                },
            )
            self.assertEqual(first.value.run_id, first_summary["run_id"])
            self.assertEqual(
                dict(first.value.seed_status_counts),
                first_summary["seed_status_counts"],
            )
            self.assertEqual(
                dict(first.value.output_sha256),
                first_summary["output_sha256"],
            )
            self.assertEqual(first.value.network_attempts, 0)
            self.assertEqual(first_network + second_network, 0)

    def test_dr05_tampered_replay_fails_with_zero_outputs(self) -> None:
        original_hashes = {
            filename: _file_hash(REAL_FIXTURE / filename)
            for filename in (
                "README.md",
                "case.json",
                "replay.json",
                "osm-pois.json",
            )
        }
        with tempfile.TemporaryDirectory(prefix="trip-decider-dor-dr05-") as temp:
            temp_root = Path(temp)
            copied_fixture = temp_root / "fixture-raw-byte"
            shutil.copytree(REAL_FIXTURE, copied_fixture)
            raw_path = copied_fixture / "osm-pois.json"
            raw = raw_path.read_bytes()
            raw_path.write_bytes(raw[:-2] + b" " + raw[-1:])
            output_root = temp_root / "output"
            output_root.mkdir()
            with patch(
                "trip_decider.resume_acquisition.replay_wu2r_resume_anchor",
                wraps=real_replay_function,
            ) as replay_mock:
                result, network_attempts = self._run(
                    copied_fixture,
                    output_root,
                )

            self.assertIsNone(result.value)
            self.assertEqual(len(result.problems), 1)
            self.assertEqual(
                result.problems[0].error_code,
                "RECOVERY_REPLAY_INVALID",
            )
            self.assertEqual(list(output_root.iterdir()), [])
            self.assertEqual(network_attempts, 0)
            self.assertEqual(replay_mock.call_count, 1)
        self.assertEqual(
            {
                filename: _file_hash(REAL_FIXTURE / filename)
                for filename in original_hashes
            },
            original_hashes,
        )

    def test_dr06_network_forbidden_and_nonempty_root_preserved(self) -> None:
        with tempfile.TemporaryDirectory(prefix="trip-decider-dor-dr06-") as temp:
            temp_root = Path(temp)
            valid_root = temp_root / "valid"
            valid, valid_network = self._run(REAL_FIXTURE, valid_root)
            blocked_root = temp_root / "blocked"
            blocked_root.mkdir()
            sentinel = blocked_root / "sentinel.bin"
            sentinel_bytes = b"caller-owned-sentinel\n"
            sentinel.write_bytes(sentinel_bytes)
            blocked, blocked_network = self._run(REAL_FIXTURE, blocked_root)

            self.assertFalse(valid.problems)
            self.assertEqual(valid.value.network_attempts, 0)
            self.assertIsNone(blocked.value)
            self.assertEqual(len(blocked.problems), 1)
            self.assertEqual(
                blocked.problems[0].error_code,
                "RECOVERY_REPLAY_INVALID",
            )
            self.assertEqual(sentinel.read_bytes(), sentinel_bytes)
            self.assertEqual(
                sorted(path.name for path in blocked_root.iterdir()),
                ["sentinel.bin"],
            )
            self.assertEqual(valid_network + blocked_network, 0)


if __name__ == "__main__":
    unittest.main()
