"""Deterministic WU1 remediation verification-entry contract cases.

Source:
    The clean and dirty inputs are synthetic deterministic validation surfaces
    written from the approved WU1R Plan.  Expected values are specification-
    authored and are never generated by the entry under test.

Coverage:
    Runtime identity, exact lock state, pip health, frozen hashes, Git scope,
    suspicious fallback and secret scans, stable problem classification,
    seven-field stderr JSONL, PowerShell transport cleanup, and the real
    success entry.

Not covered:
    Travel semantics, evidence truth, feasibility, routing, external APIs,
    optimization, rendering, or destination discovery.

This module intentionally does not match unittest's default ``test*.py``
pattern.  WU1R invokes it explicitly while the frozen WU1 entry discovery
surface remains 82 tests.
"""

from __future__ import annotations

import io
import json
import os
import subprocess
import tempfile
import unittest
from pathlib import Path
from types import SimpleNamespace

from trip_decider.schema_validation import (
    ValidationProblem,
    ValidatorInternalError,
)
from trip_decider.verification_entry import run_verification


PROJECT_ROOT = Path(__file__).resolve().parents[1]
VERIFY_SCRIPT = PROJECT_ROOT / "scripts" / "verify_wu1.ps1"
PROJECT_PYTHON = PROJECT_ROOT / ".venv" / "Scripts" / "python.exe"

LOCK_TEXT = """\
arrow==1.4.0
attrs==26.1.0
fqdn==1.5.1
idna==3.18
isoduration==20.11.0
jsonpointer==3.1.1
jsonschema==4.26.0
jsonschema-specifications==2025.9.1
lark==1.3.1
python-dateutil==2.9.0.post0
PyYAML==6.0.3
referencing==0.37.0
rfc3339-validator==0.1.4
rfc3986-validator==0.1.1
rfc3987-syntax==1.1.0
rpds-py==2026.6.3
six==1.17.0
typing_extensions==4.16.0
tzdata==2026.3
uri-template==1.3.0
webcolors==25.10.0
"""

FROZEN_HASHES = {
    "PLAN.md": "563692C54D91F431C4CF5D92FCBA6BB1CCE2DDB60857E79EEED6081D481D5456",
    "plans/work-unit-0-bootstrap-d0.md": (
        "4C7FE14CD5D2CE0CC8E8D624D93C24338EAF61A9DBC0778D101AB3565602DE3B"
    ),
    "docs/architecture.md": (
        "CA5B6F7D345E11623C94C13CDD73C0E774282AFD88F9E2E036035ED2396BB6F4"
    ),
    "docs/artifact-contracts.md": (
        "695C0AC6738B71852DC60ADAFD2A98B974C5EC65BB744D19B0E22EC3550497BF"
    ),
    "docs/prior-art.md": (
        "C1195E816DB5F21FE83B4208B6258BA9F138C9AB9404373A132CE75C457893E7"
    ),
    "docs/handbook-context.md": (
        "1933DBA1B3697A394EDCC0238B60A032A18EA10B920F8C4358169490492115EB"
    ),
    "docs/reviews/work-unit-0-review.md": (
        "D93373ECC7398DEE95FFCC04E0143DE80612B4FE948FD36282FA98F793477128"
    ),
    "plans/work-unit-1-contracts-fixtures.md": (
        "B1C2517EE7B9579EFA85C5998FA5E29170589A650CBB051F1F5C00400EB39212"
    ),
}

ORIGINAL_WU1_PATHS = (
    "docs/reviews/work-unit-1-review.md",
    "fixtures/README.md",
    "fixtures/fixture_01_feasible/README.md",
    "fixtures/fixture_01_feasible/case.json",
    "fixtures/fixture_02_direct_conflict/README.md",
    "fixtures/fixture_02_direct_conflict/case.json",
    "fixtures/fixture_03_uncertain_dependency/README.md",
    "fixtures/fixture_03_uncertain_dependency/case.json",
    "fixtures/fixture_04_replan_stability/README.md",
    "fixtures/fixture_04_replan_stability/case.json",
    "fixtures/fixture_05_evidence_state_mapping/README.md",
    "fixtures/fixture_05_evidence_state_mapping/case.json",
    "fixtures/fixture_06_no_plan_found_not_infeasible/README.md",
    "fixtures/fixture_06_no_plan_found_not_infeasible/case.json",
    "plans/work-unit-1-contracts-fixtures.md",
    "pyproject.toml",
    "requirements.lock",
    "schemas/candidates.schema.json",
    "schemas/common.schema.json",
    "schemas/constraint-parse.schema.json",
    "schemas/constraints.schema.json",
    "schemas/evidence.schema.json",
    "schemas/fixture-case.schema.json",
    "schemas/plan-diff.schema.json",
    "schemas/plan.schema.json",
    "schemas/previous-plan.schema.json",
    "schemas/request.schema.json",
    "schemas/trip-card.contract.md",
    "schemas/violations.schema.json",
    "scripts/verify_wu1.ps1",
    "src/trip_decider/__init__.py",
    "src/trip_decider/fixture_validation.py",
    "src/trip_decider/schema_validation.py",
    "tests/__init__.py",
    "tests/test_fixture_validation.py",
    "tests/test_schema_validation.py",
)

WU1R_PATHS = (
    "docs/reviews/work-unit-1-remediation-review.md",
    "plans/work-unit-1-remediation.md",
    "scripts/verify_wu1.ps1",
    "src/trip_decider/verification_entry.py",
    "tests/wu1r_verify_entry_cases.py",
)

EXPECTED_FIELDS = {
    "error_code",
    "artifact_path",
    "json_pointer",
    "schema_rule",
    "expected",
    "actual_type",
    "message",
}


def _problem(
    code: str,
    path: str,
    pointer: str,
    rule: str,
    *,
    expected: str = "",
    actual_type: str = "",
    message: str = "Specification-authored deterministic problem.",
) -> ValidationProblem:
    return ValidationProblem(
        error_code=code,
        artifact_path=path,
        json_pointer=pointer,
        schema_rule=rule,
        expected=expected,
        actual_type=actual_type,
        message=message,
    )


class FakeDependencies:
    """Clean deterministic surface with one-attribute dirty mutations."""

    def __init__(self, root: Path) -> None:
        venv = root / ".venv"
        site_packages = venv / "Lib" / "site-packages"
        packages = []
        for line in LOCK_TEXT.splitlines():
            name, version = line.split("==", 1)
            packages.append(
                {
                    "name": name,
                    "version": version,
                    "location": site_packages,
                }
            )
        packages.extend(
            [
                {"name": "pip", "version": "24.0", "location": site_packages},
                {
                    "name": "setuptools",
                    "version": "65.5.0",
                    "location": site_packages,
                },
            ]
        )
        self.runtime = {
            "executable": venv / "Scripts" / "python.exe",
            "prefix": venv,
            "site_packages": (venv, site_packages),
            "distributions": tuple(packages),
        }
        self.lock_bytes = LOCK_TEXT.encode("utf-8")
        self.pip_returncode = 0
        self.schema_observation = {
            "schema_count": 11,
            "registry": object(),
            "problems": (),
        }
        self.schema_exception: Exception | None = None
        self.unittest_observation = {
            "tests": 82,
            "failures": 0,
            "errors": 0,
            "problems": (),
        }
        self.fixture_observation = {
            "fixtures": 6,
            "documents": 38,
            "dirty_cases": 6,
            "closures": ("closed",) * 6,
            "root_artifact_ids": tuple(f"urn:uuid:{index:032x}" for index in range(6)),
            "problems": (),
        }
        self.scope = {
            "original_paths": ORIGINAL_WU1_PATHS,
            "remediation_paths": WU1R_PATHS[:-1],
            "worktree_paths": ("tests/wu1r_verify_entry_cases.py",),
            "untracked_paths": ("tests/wu1r_verify_entry_cases.py",),
        }
        self.scan_files = {
            "src/trip_decider/clean_module.py": (
                "def normalize_value(value):\n"
                "    return value\n"
            ),
            "scripts/clean.ps1": "$result = 'pass'\n",
        }
        self.hashes = dict(FROZEN_HASHES)

    def runtime_snapshot(self) -> dict[str, object]:
        return self.runtime

    def read_lock(self, path: Path) -> bytes:
        del path
        return self.lock_bytes

    def run_pip_check(self) -> int:
        return self.pip_returncode

    def check_schemas(self, root: Path) -> dict[str, object]:
        del root
        if self.schema_exception is not None:
            raise self.schema_exception
        return self.schema_observation

    def run_unittest_discovery(self, root: Path) -> dict[str, object]:
        del root
        return self.unittest_observation

    def check_fixtures(self, root: Path, registry: object) -> dict[str, object]:
        del root, registry
        return self.fixture_observation

    def scope_snapshot(self, root: Path) -> dict[str, object]:
        del root
        return self.scope

    def source_files(self, root: Path) -> dict[str, str]:
        del root
        return self.scan_files

    def frozen_hashes(
        self,
        root: Path,
        expected_paths: tuple[str, ...],
    ) -> dict[str, str]:
        del root
        return {path: self.hashes[path] for path in expected_paths}


class VerificationEntryContractTest(unittest.TestCase):
    maxDiff = None

    def _run(
        self,
        dependencies: FakeDependencies,
    ) -> tuple[int, str, str]:
        stdout = io.StringIO()
        stderr = io.StringIO()
        code = run_verification(
            PROJECT_ROOT,
            dependencies=dependencies,
            stdout=stdout,
            stderr=stderr,
        )
        return code, stdout.getvalue(), stderr.getvalue()

    def _machine_lines(self, stderr: str) -> list[dict[str, object]]:
        lines = stderr.splitlines()
        self.assertGreaterEqual(len(lines), 1)
        values = [json.loads(line) for line in lines]
        for value in values:
            self.assertEqual(set(value), EXPECTED_FIELDS)
        return values

    def test_ve_01_non_project_executable_exits_5(self) -> None:
        deps = FakeDependencies(PROJECT_ROOT)
        deps.runtime["executable"] = Path("C:/Python311/python.exe")
        code, stdout, stderr = self._run(deps)
        problem = self._machine_lines(stderr)[0]
        self.assertEqual(code, 5)
        self.assertEqual(problem["error_code"], "ENTRY_RUNTIME_IDENTITY_ERROR")
        self.assertEqual(problem["artifact_path"], ".venv")
        self.assertNotIn("C:/Python311", stdout + stderr)

    def test_ve_02_prefix_or_site_packages_outside_venv_exits_5(self) -> None:
        for field, value in (
            ("prefix", Path("C:/Python311")),
            (
                "site_packages",
                (PROJECT_ROOT / ".venv", Path("C:/Python311/Lib/site-packages")),
            ),
        ):
            with self.subTest(field=field):
                deps = FakeDependencies(PROJECT_ROOT)
                deps.runtime[field] = value
                code, stdout, stderr = self._run(deps)
                problem = self._machine_lines(stderr)[0]
                self.assertEqual(code, 5)
                self.assertEqual(
                    problem["error_code"],
                    "ENTRY_RUNTIME_IDENTITY_ERROR",
                )
                self.assertNotIn("C:/Python311", stdout + stderr)

    def test_ve_03_lock_runtime_mismatch_exits_5(self) -> None:
        deps = FakeDependencies(PROJECT_ROOT)
        packages = list(deps.runtime["distributions"])
        packages[0] = dict(packages[0], version="0.0.0")
        deps.runtime["distributions"] = tuple(packages)
        code, stdout, stderr = self._run(deps)
        problem = self._machine_lines(stderr)[0]
        self.assertEqual(code, 5)
        self.assertEqual(problem["error_code"], "ENTRY_LOCK_MISMATCH")
        self.assertEqual(problem["expected"], "exact requirements.lock package set")
        self.assertNotIn("0.0.0", stdout + stderr)

    def test_ve_04_pip_check_failure_is_sanitized_and_exits_5(self) -> None:
        deps = FakeDependencies(PROJECT_ROOT)
        deps.pip_returncode = 1
        marker = "dependency-conflict-private-value"
        code, stdout, stderr = self._run(deps)
        problem = self._machine_lines(stderr)[0]
        self.assertEqual(code, 5)
        self.assertEqual(problem["error_code"], "ENTRY_PIP_CHECK_FAILED")
        self.assertEqual(problem["schema_rule"], "pipCheck")
        self.assertNotIn(marker, stdout + stderr)

    def test_ve_05_frozen_hash_change_exits_2_without_hash_values(self) -> None:
        deps = FakeDependencies(PROJECT_ROOT)
        path = "PLAN.md"
        approved = FROZEN_HASHES[path]
        changed = "0" * 64
        deps.hashes[path] = changed
        code, stdout, stderr = self._run(deps)
        problem = self._machine_lines(stderr)[0]
        self.assertEqual(code, 2)
        self.assertEqual(problem["error_code"], "ENTRY_FROZEN_HASH_MISMATCH")
        self.assertEqual(problem["artifact_path"], path)
        self.assertNotIn(approved, stdout + stderr)
        self.assertNotIn(changed, stdout + stderr)

    def test_ve_06_extra_scope_path_exits_5(self) -> None:
        deps = FakeDependencies(PROJECT_ROOT)
        extra = "src/trip_decider/extra.py"
        deps.scope["worktree_paths"] = (
            "tests/wu1r_verify_entry_cases.py",
            extra,
        )
        deps.scope["untracked_paths"] = (extra,)
        code, stdout, stderr = self._run(deps)
        problem = self._machine_lines(stderr)[0]
        self.assertEqual(code, 5)
        self.assertEqual(problem["error_code"], "ENTRY_SCOPE_VIOLATION")
        self.assertEqual(problem["artifact_path"], extra)
        self.assertNotIn("{", stdout)

    def test_ve_07_suspicious_function_scan_hit_exits_5(self) -> None:
        deps = FakeDependencies(PROJECT_ROOT)
        path = "src/trip_decider/dirty_module.py"
        deps.scan_files[path] = "def guess_route(value):\n    return value\n"
        code, stdout, stderr = self._run(deps)
        problem = self._machine_lines(stderr)[0]
        self.assertEqual(code, 5)
        self.assertEqual(problem["error_code"], "ENTRY_FALLBACK_SCAN_HIT")
        self.assertEqual(problem["artifact_path"], path)
        self.assertEqual(problem["actual_type"], "function-name")
        self.assertNotIn("guess_route", stdout + stderr)

    def test_ve_08_secret_scan_hit_exits_5_without_value(self) -> None:
        deps = FakeDependencies(PROJECT_ROOT)
        path = "config/dirty.env"
        secret_marker = "AMAP_" + "API_KEY=" + ("x" * 32)
        deps.scan_files[path] = secret_marker + "\n"
        code, stdout, stderr = self._run(deps)
        problem = self._machine_lines(stderr)[0]
        self.assertEqual(code, 5)
        self.assertEqual(problem["error_code"], "ENTRY_SECRET_SCAN_HIT")
        self.assertEqual(problem["artifact_path"], path)
        self.assertEqual(problem["actual_type"], "credential-pattern")
        self.assertNotIn(secret_marker, stdout + stderr)

    def test_ve_09_artifact_problem_is_seven_fields_on_stderr_exit_2(self) -> None:
        deps = FakeDependencies(PROJECT_ROOT)
        deps.schema_observation["problems"] = (
            _problem(
                "SCHEMA_VALIDATION_ERROR",
                "schemas/plan.schema.json",
                "/$id",
                "const",
            ),
        )
        code, stdout, stderr = self._run(deps)
        problem = self._machine_lines(stderr)[0]
        self.assertEqual(code, 2)
        self.assertEqual(problem["error_code"], "SCHEMA_VALIDATION_ERROR")
        self.assertEqual(problem["json_pointer"], "/$id")
        self.assertNotIn("{", stdout)

    def test_ve_10_fixture_manifest_problem_exits_3(self) -> None:
        deps = FakeDependencies(PROJECT_ROOT)
        deps.fixture_observation["problems"] = (
            _problem(
                "FIXTURE_EXPECTATION_MISMATCH",
                "fixtures/fixture_01_feasible/case.json",
                "/dirty_cases/0/expected_error",
                "expectedError",
            ),
        )
        code, stdout, stderr = self._run(deps)
        problem = self._machine_lines(stderr)[0]
        self.assertEqual(code, 3)
        self.assertEqual(problem["error_code"], "FIXTURE_EXPECTATION_MISMATCH")
        self.assertEqual(problem["schema_rule"], "expectedError")
        self.assertNotIn("{", stdout)

    def test_ve_11_input_or_parse_problem_exits_4(self) -> None:
        deps = FakeDependencies(PROJECT_ROOT)
        deps.schema_observation["problems"] = (
            _problem(
                "INVALID_JSON",
                "schemas/plan.schema.json",
                "",
                "jsonSyntax",
            ),
        )
        code, stdout, stderr = self._run(deps)
        problem = self._machine_lines(stderr)[0]
        self.assertEqual(code, 4)
        self.assertEqual(problem["error_code"], "INVALID_JSON")
        self.assertEqual(problem["artifact_path"], "schemas/plan.schema.json")
        self.assertNotIn("Traceback", stdout + stderr)

    def test_ve_12_registry_internal_problem_is_sanitized_and_exits_5(self) -> None:
        deps = FakeDependencies(PROJECT_ROOT)
        private_marker = "third-party-private-exception"
        deps.schema_exception = ValidatorInternalError(private_marker)
        code, stdout, stderr = self._run(deps)
        problem = self._machine_lines(stderr)[0]
        self.assertEqual(code, 5)
        self.assertEqual(problem["error_code"], "ENTRY_REGISTRY_INTERNAL_ERROR")
        self.assertEqual(problem["artifact_path"], "schemas")
        self.assertNotIn(private_marker, stdout + stderr)

    def test_ve_13_fixture_artifact_problem_remains_exit_2(self) -> None:
        deps = FakeDependencies(PROJECT_ROOT)
        deps.fixture_observation["problems"] = (
            _problem(
                "UNRESOLVED_REFERENCE",
                "fixtures/fixture_01_feasible/case.json",
                "/documents/2",
                "referenceIdentity",
            ),
        )
        code, stdout, stderr = self._run(deps)
        problem = self._machine_lines(stderr)[0]
        self.assertEqual(code, 2)
        self.assertEqual(problem["error_code"], "UNRESOLVED_REFERENCE")
        self.assertEqual(problem["schema_rule"], "referenceIdentity")
        self.assertNotIn("{", stdout)

    def test_ve_14_mixed_problem_priority_and_jsonl_order_are_stable(self) -> None:
        deps = FakeDependencies(PROJECT_ROOT)
        deps.fixture_observation["problems"] = (
            _problem("FIXTURE_MUTATION_ERROR", "z.json", "/b", "mutation"),
            _problem("SCHEMA_VALIDATION_ERROR", "a.json", "/z", "type"),
            _problem("INVALID_YAML", "a.json", "/a", "yamlSyntax"),
            _problem("UNRECOGNIZED_FUTURE_CODE", "m.json", "", "future"),
        )
        code, stdout, stderr = self._run(deps)
        problems = self._machine_lines(stderr)
        keys = [
            (
                value["artifact_path"],
                value["json_pointer"],
                value["error_code"],
            )
            for value in problems
        ]
        self.assertEqual(code, 5)
        self.assertEqual(keys, sorted(keys))
        self.assertEqual(
            [value["error_code"] for value in problems],
            [
                "INVALID_YAML",
                "SCHEMA_VALIDATION_ERROR",
                "ENTRY_UNCLASSIFIED_PROBLEM",
                "FIXTURE_MUTATION_ERROR",
            ],
        )
        self.assertNotIn("{", stdout)

    def test_ve_15_stdout_is_human_and_stderr_lines_have_exact_fields(self) -> None:
        deps = FakeDependencies(PROJECT_ROOT)
        secret_value = "input-value-must-not-appear"
        deps.schema_observation["problems"] = (
            _problem(
                "PAYLOAD_HASH_MISMATCH",
                "plan.json",
                "/integrity/payload_sha256",
                "canonicalPayloadHash",
                expected="canonical payload hash",
                actual_type="string",
                message="Artifact payload hash does not match canonical payload.",
            ),
        )
        code, stdout, stderr = self._run(deps)
        problems = self._machine_lines(stderr)
        self.assertEqual(code, 2)
        self.assertEqual(len(problems), 1)
        self.assertEqual(set(problems[0]), EXPECTED_FIELDS)
        self.assertNotIn("{", stdout)
        self.assertNotIn("Traceback", stderr)
        self.assertNotIn(secret_value, stdout + stderr)

    def test_ve_16_success_transport_leaves_no_temp_python(self) -> None:
        temp_root = Path(tempfile.gettempdir())
        pattern = "trip-decider-wu1-*.py"
        before = {path.resolve() for path in temp_root.glob(pattern)}
        result = subprocess.run(
            [
                "powershell",
                "-NoProfile",
                "-ExecutionPolicy",
                "Bypass",
                "-File",
                str(VERIFY_SCRIPT),
            ],
            cwd=PROJECT_ROOT,
            text=True,
            capture_output=True,
            check=False,
        )
        after = {path.resolve() for path in temp_root.glob(pattern)}
        self.assertEqual(result.returncode, 0)
        self.assertEqual(after, before)
        self.assertFalse(any(PROJECT_ROOT.rglob("trip-decider-wu1-*.py")))

    def test_ve_17_failed_transport_leaves_no_temp_python(self) -> None:
        temp_root = Path(tempfile.gettempdir())
        before = {
            path.resolve()
            for path in temp_root.glob("trip-decider-wu1-*.py")
        }
        script_literal = str(VERIFY_SCRIPT).replace("'", "''")
        python_literal = str(PROJECT_PYTHON).replace("'", "''")
        root_literal = str(PROJECT_ROOT).replace("'", "''")
        harness = (
            "$ErrorActionPreference = 'Stop'\n"
            f". '{script_literal}'\n"
            "$code = \"raise SystemExit(5)\"\n"
            "$result = Invoke-Wu1PythonTransport "
            f"-PythonExe '{python_literal}' "
            "-PythonCode $code "
            f"-RepoRoot '{root_literal}'\n"
            "exit $result\n"
        )
        handle, harness_path_value = tempfile.mkstemp(
            prefix="trip-decider-wu1r-",
            suffix=".ps1",
        )
        os.close(handle)
        harness_path = Path(harness_path_value)
        try:
            harness_path.write_text(harness, encoding="utf-8", newline="\n")
            result = subprocess.run(
                [
                    "powershell",
                    "-NoProfile",
                    "-ExecutionPolicy",
                    "Bypass",
                    "-File",
                    str(harness_path),
                ],
                cwd=PROJECT_ROOT,
                text=True,
                capture_output=True,
                check=False,
            )
        finally:
            harness_path.unlink(missing_ok=True)
        after = {
            path.resolve()
            for path in temp_root.glob("trip-decider-wu1-*.py")
        }
        self.assertEqual(result.returncode, 5)
        self.assertEqual(after, before)
        self.assertFalse(any(PROJECT_ROOT.rglob("trip-decider-wu1-*.py")))

    def test_ve_18_real_entry_reports_frozen_success_surface(self) -> None:
        result = subprocess.run(
            [
                "powershell",
                "-NoProfile",
                "-ExecutionPolicy",
                "Bypass",
                "-File",
                str(VERIFY_SCRIPT),
            ],
            cwd=PROJECT_ROOT,
            text=True,
            capture_output=True,
            check=False,
        )
        self.assertEqual(result.returncode, 0)
        self.assertEqual(result.stderr, "")
        self.assertEqual(
            result.stdout.strip(),
            (
                "WU1 verification PASS: schemas=11 tests=82 fixtures=6 "
                "documents=38 dirty_cases=6"
            ),
        )


if __name__ == "__main__":
    unittest.main()
